// Code generated by MockGen. DO NOT EDIT.
// Source: mall/search/internal/application (interfaces: Application)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mock.go -package=application mall/search/internal/application Application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	domain "mall/search/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApplication is a mock of Application interface.
type MockApplication struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationMockRecorder
	isgomock struct{}
}

// MockApplicationMockRecorder is the mock recorder for MockApplication.
type MockApplicationMockRecorder struct {
	mock *MockApplication
}

// NewMockApplication creates a new mock instance.
func NewMockApplication(ctrl *gomock.Controller) *MockApplication {
	mock := &MockApplication{ctrl: ctrl}
	mock.recorder = &MockApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplication) EXPECT() *MockApplicationMockRecorder {
	return m.recorder
}

// GetOrder mocks base method.
func (m *MockApplication) GetOrder(ctx context.Context, get domain.GetOrder) (*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, get)
	ret0, _ := ret[0].(*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockApplicationMockRecorder) GetOrder(ctx, get any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockApplication)(nil).GetOrder), ctx, get)
}

// SearchOrders mocks base method.
func (m *MockApplication) SearchOrders(ctx context.Context, search domain.SearchOrders) ([]*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchOrders", ctx, search)
	ret0, _ := ret[0].([]*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchOrders indicates an expected call of SearchOrders.
func (mr *MockApplicationMockRecorder) SearchOrders(ctx, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchOrders", reflect.TypeOf((*MockApplication)(nil).SearchOrders), ctx, search)
}
