// Code generated by MockGen. DO NOT EDIT.
// Source: mall/stores/storespb (interfaces: StoresServiceClient,StoresServiceServer)
//
// Generated by this command:
//
//	mockgen -destination=storespb/mock.go -package=storespb mall/stores/storespb StoresServiceClient,StoresServiceServer
//

// Package storespb is a generated GoMock package.
package storespb

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockStoresServiceClient is a mock of StoresServiceClient interface.
type MockStoresServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockStoresServiceClientMockRecorder
	isgomock struct{}
}

// MockStoresServiceClientMockRecorder is the mock recorder for MockStoresServiceClient.
type MockStoresServiceClientMockRecorder struct {
	mock *MockStoresServiceClient
}

// NewMockStoresServiceClient creates a new mock instance.
func NewMockStoresServiceClient(ctrl *gomock.Controller) *MockStoresServiceClient {
	mock := &MockStoresServiceClient{ctrl: ctrl}
	mock.recorder = &MockStoresServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoresServiceClient) EXPECT() *MockStoresServiceClientMockRecorder {
	return m.recorder
}

// AddProduct mocks base method.
func (m *MockStoresServiceClient) AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddProduct", varargs...)
	ret0, _ := ret[0].(*AddProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockStoresServiceClientMockRecorder) AddProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockStoresServiceClient)(nil).AddProduct), varargs...)
}

// CreateStore mocks base method.
func (m *MockStoresServiceClient) CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*CreateStoreResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateStore", varargs...)
	ret0, _ := ret[0].(*CreateStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockStoresServiceClientMockRecorder) CreateStore(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockStoresServiceClient)(nil).CreateStore), varargs...)
}

// DecreaseProductPrice mocks base method.
func (m *MockStoresServiceClient) DecreaseProductPrice(ctx context.Context, in *DecreaseProductPriceRequest, opts ...grpc.CallOption) (*DecreaseProductPriceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DecreaseProductPrice", varargs...)
	ret0, _ := ret[0].(*DecreaseProductPriceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecreaseProductPrice indicates an expected call of DecreaseProductPrice.
func (mr *MockStoresServiceClientMockRecorder) DecreaseProductPrice(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseProductPrice", reflect.TypeOf((*MockStoresServiceClient)(nil).DecreaseProductPrice), varargs...)
}

// DisableParticipation mocks base method.
func (m *MockStoresServiceClient) DisableParticipation(ctx context.Context, in *DisableParticipationRequest, opts ...grpc.CallOption) (*DisableParticipationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DisableParticipation", varargs...)
	ret0, _ := ret[0].(*DisableParticipationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableParticipation indicates an expected call of DisableParticipation.
func (mr *MockStoresServiceClientMockRecorder) DisableParticipation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableParticipation", reflect.TypeOf((*MockStoresServiceClient)(nil).DisableParticipation), varargs...)
}

// EnableParticipation mocks base method.
func (m *MockStoresServiceClient) EnableParticipation(ctx context.Context, in *EnableParticipationRequest, opts ...grpc.CallOption) (*EnableParticipationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EnableParticipation", varargs...)
	ret0, _ := ret[0].(*EnableParticipationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableParticipation indicates an expected call of EnableParticipation.
func (mr *MockStoresServiceClientMockRecorder) EnableParticipation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableParticipation", reflect.TypeOf((*MockStoresServiceClient)(nil).EnableParticipation), varargs...)
}

// GetCatalog mocks base method.
func (m *MockStoresServiceClient) GetCatalog(ctx context.Context, in *GetCatalogRequest, opts ...grpc.CallOption) (*GetCatalogResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCatalog", varargs...)
	ret0, _ := ret[0].(*GetCatalogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCatalog indicates an expected call of GetCatalog.
func (mr *MockStoresServiceClientMockRecorder) GetCatalog(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCatalog", reflect.TypeOf((*MockStoresServiceClient)(nil).GetCatalog), varargs...)
}

// GetParticipatingStores mocks base method.
func (m *MockStoresServiceClient) GetParticipatingStores(ctx context.Context, in *GetParticipatingStoresRequest, opts ...grpc.CallOption) (*GetParticipatingStoresResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetParticipatingStores", varargs...)
	ret0, _ := ret[0].(*GetParticipatingStoresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipatingStores indicates an expected call of GetParticipatingStores.
func (mr *MockStoresServiceClientMockRecorder) GetParticipatingStores(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipatingStores", reflect.TypeOf((*MockStoresServiceClient)(nil).GetParticipatingStores), varargs...)
}

// GetProduct mocks base method.
func (m *MockStoresServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProduct", varargs...)
	ret0, _ := ret[0].(*GetProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockStoresServiceClientMockRecorder) GetProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockStoresServiceClient)(nil).GetProduct), varargs...)
}

// GetStore mocks base method.
func (m *MockStoresServiceClient) GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*GetStoreResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStore", varargs...)
	ret0, _ := ret[0].(*GetStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStore indicates an expected call of GetStore.
func (mr *MockStoresServiceClientMockRecorder) GetStore(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockStoresServiceClient)(nil).GetStore), varargs...)
}

// GetStores mocks base method.
func (m *MockStoresServiceClient) GetStores(ctx context.Context, in *GetStoresRequest, opts ...grpc.CallOption) (*GetStoresResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStores", varargs...)
	ret0, _ := ret[0].(*GetStoresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStores indicates an expected call of GetStores.
func (mr *MockStoresServiceClientMockRecorder) GetStores(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStores", reflect.TypeOf((*MockStoresServiceClient)(nil).GetStores), varargs...)
}

// IncreaseProductPrice mocks base method.
func (m *MockStoresServiceClient) IncreaseProductPrice(ctx context.Context, in *IncreaseProductPriceRequest, opts ...grpc.CallOption) (*IncreaseProductPriceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IncreaseProductPrice", varargs...)
	ret0, _ := ret[0].(*IncreaseProductPriceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseProductPrice indicates an expected call of IncreaseProductPrice.
func (mr *MockStoresServiceClientMockRecorder) IncreaseProductPrice(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseProductPrice", reflect.TypeOf((*MockStoresServiceClient)(nil).IncreaseProductPrice), varargs...)
}

// RebrandProduct mocks base method.
func (m *MockStoresServiceClient) RebrandProduct(ctx context.Context, in *RebrandProductRequest, opts ...grpc.CallOption) (*RebrandProductResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RebrandProduct", varargs...)
	ret0, _ := ret[0].(*RebrandProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RebrandProduct indicates an expected call of RebrandProduct.
func (mr *MockStoresServiceClientMockRecorder) RebrandProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebrandProduct", reflect.TypeOf((*MockStoresServiceClient)(nil).RebrandProduct), varargs...)
}

// RebrandStore mocks base method.
func (m *MockStoresServiceClient) RebrandStore(ctx context.Context, in *RebrandStoreRequest, opts ...grpc.CallOption) (*RebrandStoreResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RebrandStore", varargs...)
	ret0, _ := ret[0].(*RebrandStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RebrandStore indicates an expected call of RebrandStore.
func (mr *MockStoresServiceClientMockRecorder) RebrandStore(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebrandStore", reflect.TypeOf((*MockStoresServiceClient)(nil).RebrandStore), varargs...)
}

// RemoveProduct mocks base method.
func (m *MockStoresServiceClient) RemoveProduct(ctx context.Context, in *RemoveProductRequest, opts ...grpc.CallOption) (*RemoveProductResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveProduct", varargs...)
	ret0, _ := ret[0].(*RemoveProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveProduct indicates an expected call of RemoveProduct.
func (mr *MockStoresServiceClientMockRecorder) RemoveProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveProduct", reflect.TypeOf((*MockStoresServiceClient)(nil).RemoveProduct), varargs...)
}

// MockStoresServiceServer is a mock of StoresServiceServer interface.
type MockStoresServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockStoresServiceServerMockRecorder
	isgomock struct{}
}

// MockStoresServiceServerMockRecorder is the mock recorder for MockStoresServiceServer.
type MockStoresServiceServerMockRecorder struct {
	mock *MockStoresServiceServer
}

// NewMockStoresServiceServer creates a new mock instance.
func NewMockStoresServiceServer(ctrl *gomock.Controller) *MockStoresServiceServer {
	mock := &MockStoresServiceServer{ctrl: ctrl}
	mock.recorder = &MockStoresServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoresServiceServer) EXPECT() *MockStoresServiceServerMockRecorder {
	return m.recorder
}

// AddProduct mocks base method.
func (m *MockStoresServiceServer) AddProduct(arg0 context.Context, arg1 *AddProductRequest) (*AddProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", arg0, arg1)
	ret0, _ := ret[0].(*AddProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockStoresServiceServerMockRecorder) AddProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockStoresServiceServer)(nil).AddProduct), arg0, arg1)
}

// CreateStore mocks base method.
func (m *MockStoresServiceServer) CreateStore(arg0 context.Context, arg1 *CreateStoreRequest) (*CreateStoreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStore", arg0, arg1)
	ret0, _ := ret[0].(*CreateStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockStoresServiceServerMockRecorder) CreateStore(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockStoresServiceServer)(nil).CreateStore), arg0, arg1)
}

// DecreaseProductPrice mocks base method.
func (m *MockStoresServiceServer) DecreaseProductPrice(arg0 context.Context, arg1 *DecreaseProductPriceRequest) (*DecreaseProductPriceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseProductPrice", arg0, arg1)
	ret0, _ := ret[0].(*DecreaseProductPriceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecreaseProductPrice indicates an expected call of DecreaseProductPrice.
func (mr *MockStoresServiceServerMockRecorder) DecreaseProductPrice(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseProductPrice", reflect.TypeOf((*MockStoresServiceServer)(nil).DecreaseProductPrice), arg0, arg1)
}

// DisableParticipation mocks base method.
func (m *MockStoresServiceServer) DisableParticipation(arg0 context.Context, arg1 *DisableParticipationRequest) (*DisableParticipationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableParticipation", arg0, arg1)
	ret0, _ := ret[0].(*DisableParticipationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableParticipation indicates an expected call of DisableParticipation.
func (mr *MockStoresServiceServerMockRecorder) DisableParticipation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableParticipation", reflect.TypeOf((*MockStoresServiceServer)(nil).DisableParticipation), arg0, arg1)
}

// EnableParticipation mocks base method.
func (m *MockStoresServiceServer) EnableParticipation(arg0 context.Context, arg1 *EnableParticipationRequest) (*EnableParticipationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableParticipation", arg0, arg1)
	ret0, _ := ret[0].(*EnableParticipationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableParticipation indicates an expected call of EnableParticipation.
func (mr *MockStoresServiceServerMockRecorder) EnableParticipation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableParticipation", reflect.TypeOf((*MockStoresServiceServer)(nil).EnableParticipation), arg0, arg1)
}

// GetCatalog mocks base method.
func (m *MockStoresServiceServer) GetCatalog(arg0 context.Context, arg1 *GetCatalogRequest) (*GetCatalogResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCatalog", arg0, arg1)
	ret0, _ := ret[0].(*GetCatalogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCatalog indicates an expected call of GetCatalog.
func (mr *MockStoresServiceServerMockRecorder) GetCatalog(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCatalog", reflect.TypeOf((*MockStoresServiceServer)(nil).GetCatalog), arg0, arg1)
}

// GetParticipatingStores mocks base method.
func (m *MockStoresServiceServer) GetParticipatingStores(arg0 context.Context, arg1 *GetParticipatingStoresRequest) (*GetParticipatingStoresResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipatingStores", arg0, arg1)
	ret0, _ := ret[0].(*GetParticipatingStoresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipatingStores indicates an expected call of GetParticipatingStores.
func (mr *MockStoresServiceServerMockRecorder) GetParticipatingStores(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipatingStores", reflect.TypeOf((*MockStoresServiceServer)(nil).GetParticipatingStores), arg0, arg1)
}

// GetProduct mocks base method.
func (m *MockStoresServiceServer) GetProduct(arg0 context.Context, arg1 *GetProductRequest) (*GetProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", arg0, arg1)
	ret0, _ := ret[0].(*GetProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockStoresServiceServerMockRecorder) GetProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockStoresServiceServer)(nil).GetProduct), arg0, arg1)
}

// GetStore mocks base method.
func (m *MockStoresServiceServer) GetStore(arg0 context.Context, arg1 *GetStoreRequest) (*GetStoreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore", arg0, arg1)
	ret0, _ := ret[0].(*GetStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStore indicates an expected call of GetStore.
func (mr *MockStoresServiceServerMockRecorder) GetStore(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockStoresServiceServer)(nil).GetStore), arg0, arg1)
}

// GetStores mocks base method.
func (m *MockStoresServiceServer) GetStores(arg0 context.Context, arg1 *GetStoresRequest) (*GetStoresResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStores", arg0, arg1)
	ret0, _ := ret[0].(*GetStoresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStores indicates an expected call of GetStores.
func (mr *MockStoresServiceServerMockRecorder) GetStores(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStores", reflect.TypeOf((*MockStoresServiceServer)(nil).GetStores), arg0, arg1)
}

// IncreaseProductPrice mocks base method.
func (m *MockStoresServiceServer) IncreaseProductPrice(arg0 context.Context, arg1 *IncreaseProductPriceRequest) (*IncreaseProductPriceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseProductPrice", arg0, arg1)
	ret0, _ := ret[0].(*IncreaseProductPriceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseProductPrice indicates an expected call of IncreaseProductPrice.
func (mr *MockStoresServiceServerMockRecorder) IncreaseProductPrice(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseProductPrice", reflect.TypeOf((*MockStoresServiceServer)(nil).IncreaseProductPrice), arg0, arg1)
}

// RebrandProduct mocks base method.
func (m *MockStoresServiceServer) RebrandProduct(arg0 context.Context, arg1 *RebrandProductRequest) (*RebrandProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebrandProduct", arg0, arg1)
	ret0, _ := ret[0].(*RebrandProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RebrandProduct indicates an expected call of RebrandProduct.
func (mr *MockStoresServiceServerMockRecorder) RebrandProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebrandProduct", reflect.TypeOf((*MockStoresServiceServer)(nil).RebrandProduct), arg0, arg1)
}

// RebrandStore mocks base method.
func (m *MockStoresServiceServer) RebrandStore(arg0 context.Context, arg1 *RebrandStoreRequest) (*RebrandStoreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebrandStore", arg0, arg1)
	ret0, _ := ret[0].(*RebrandStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RebrandStore indicates an expected call of RebrandStore.
func (mr *MockStoresServiceServerMockRecorder) RebrandStore(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebrandStore", reflect.TypeOf((*MockStoresServiceServer)(nil).RebrandStore), arg0, arg1)
}

// RemoveProduct mocks base method.
func (m *MockStoresServiceServer) RemoveProduct(arg0 context.Context, arg1 *RemoveProductRequest) (*RemoveProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveProduct", arg0, arg1)
	ret0, _ := ret[0].(*RemoveProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveProduct indicates an expected call of RemoveProduct.
func (mr *MockStoresServiceServerMockRecorder) RemoveProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveProduct", reflect.TypeOf((*MockStoresServiceServer)(nil).RemoveProduct), arg0, arg1)
}

// mustEmbedUnimplementedStoresServiceServer mocks base method.
func (m *MockStoresServiceServer) mustEmbedUnimplementedStoresServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedStoresServiceServer")
}

// mustEmbedUnimplementedStoresServiceServer indicates an expected call of mustEmbedUnimplementedStoresServiceServer.
func (mr *MockStoresServiceServerMockRecorder) mustEmbedUnimplementedStoresServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedStoresServiceServer", reflect.TypeOf((*MockStoresServiceServer)(nil).mustEmbedUnimplementedStoresServiceServer))
}
