// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: message_types.proto

package am

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventMessageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessageData) Reset() {
	*x = EventMessageData{}
	mi := &file_message_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessageData) ProtoMessage() {}

func (x *EventMessageData) ProtoReflect() protoreflect.Message {
	mi := &file_message_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessageData.ProtoReflect.Descriptor instead.
func (*EventMessageData) Descriptor() ([]byte, []int) {
	return file_message_types_proto_rawDescGZIP(), []int{0}
}

func (x *EventMessageData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventMessageData) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *EventMessageData) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_message_types_proto protoreflect.FileDescriptor

const file_message_types_proto_rawDesc = "" +
	"\n" +
	"\x13message_types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x9e\x01\n" +
	"\x10EventMessageData\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadataB'B\x11MessageTypesProtoP\x01Z\x10mall/internal/amb\x06proto3"

var (
	file_message_types_proto_rawDescOnce sync.Once
	file_message_types_proto_rawDescData []byte
)

func file_message_types_proto_rawDescGZIP() []byte {
	file_message_types_proto_rawDescOnce.Do(func() {
		file_message_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_types_proto_rawDesc), len(file_message_types_proto_rawDesc)))
	})
	return file_message_types_proto_rawDescData
}

var file_message_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_types_proto_goTypes = []any{
	(*EventMessageData)(nil),      // 0: EventMessageData
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 2: google.protobuf.Struct
}
var file_message_types_proto_depIdxs = []int32{
	1, // 0: EventMessageData.occurred_at:type_name -> google.protobuf.Timestamp
	2, // 1: EventMessageData.metadata:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_types_proto_init() }
func file_message_types_proto_init() {
	if File_message_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_types_proto_rawDesc), len(file_message_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_types_proto_goTypes,
		DependencyIndexes: file_message_types_proto_depIdxs,
		MessageInfos:      file_message_types_proto_msgTypes,
	}.Build()
	File_message_types_proto = out.File
	file_message_types_proto_goTypes = nil
	file_message_types_proto_depIdxs = nil
}
