// Code generated by MockGen. DO NOT EDIT.
// Source: mall/baskets/basketspb (interfaces: BasketServiceClient,BasketServiceServer)
//
// Generated by this command:
//
//	mockgen -destination=basketspb/mock.go -package=basketspb mall/baskets/basketspb BasketServiceClient,BasketServiceServer
//

// Package basketspb is a generated GoMock package.
package basketspb

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockBasketServiceClient is a mock of BasketServiceClient interface.
type MockBasketServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBasketServiceClientMockRecorder
	isgomock struct{}
}

// MockBasketServiceClientMockRecorder is the mock recorder for MockBasketServiceClient.
type MockBasketServiceClientMockRecorder struct {
	mock *MockBasketServiceClient
}

// NewMockBasketServiceClient creates a new mock instance.
func NewMockBasketServiceClient(ctrl *gomock.Controller) *MockBasketServiceClient {
	mock := &MockBasketServiceClient{ctrl: ctrl}
	mock.recorder = &MockBasketServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasketServiceClient) EXPECT() *MockBasketServiceClientMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockBasketServiceClient) AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*AddItemResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddItem", varargs...)
	ret0, _ := ret[0].(*AddItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddItem indicates an expected call of AddItem.
func (mr *MockBasketServiceClientMockRecorder) AddItem(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockBasketServiceClient)(nil).AddItem), varargs...)
}

// CancelBasket mocks base method.
func (m *MockBasketServiceClient) CancelBasket(ctx context.Context, in *CancelBasketRequest, opts ...grpc.CallOption) (*CancelBasketResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelBasket", varargs...)
	ret0, _ := ret[0].(*CancelBasketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelBasket indicates an expected call of CancelBasket.
func (mr *MockBasketServiceClientMockRecorder) CancelBasket(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBasket", reflect.TypeOf((*MockBasketServiceClient)(nil).CancelBasket), varargs...)
}

// CheckoutBasket mocks base method.
func (m *MockBasketServiceClient) CheckoutBasket(ctx context.Context, in *CheckoutBasketRequest, opts ...grpc.CallOption) (*CheckoutBasketResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckoutBasket", varargs...)
	ret0, _ := ret[0].(*CheckoutBasketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckoutBasket indicates an expected call of CheckoutBasket.
func (mr *MockBasketServiceClientMockRecorder) CheckoutBasket(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutBasket", reflect.TypeOf((*MockBasketServiceClient)(nil).CheckoutBasket), varargs...)
}

// GetBasket mocks base method.
func (m *MockBasketServiceClient) GetBasket(ctx context.Context, in *GetBasketRequest, opts ...grpc.CallOption) (*GetBasketResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBasket", varargs...)
	ret0, _ := ret[0].(*GetBasketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasket indicates an expected call of GetBasket.
func (mr *MockBasketServiceClientMockRecorder) GetBasket(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasket", reflect.TypeOf((*MockBasketServiceClient)(nil).GetBasket), varargs...)
}

// RemoveItem mocks base method.
func (m *MockBasketServiceClient) RemoveItem(ctx context.Context, in *RemoveItemRequest, opts ...grpc.CallOption) (*RemoveItemResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveItem", varargs...)
	ret0, _ := ret[0].(*RemoveItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockBasketServiceClientMockRecorder) RemoveItem(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockBasketServiceClient)(nil).RemoveItem), varargs...)
}

// StartBasket mocks base method.
func (m *MockBasketServiceClient) StartBasket(ctx context.Context, in *StartBasketRequest, opts ...grpc.CallOption) (*StartBasketResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartBasket", varargs...)
	ret0, _ := ret[0].(*StartBasketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartBasket indicates an expected call of StartBasket.
func (mr *MockBasketServiceClientMockRecorder) StartBasket(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBasket", reflect.TypeOf((*MockBasketServiceClient)(nil).StartBasket), varargs...)
}

// MockBasketServiceServer is a mock of BasketServiceServer interface.
type MockBasketServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockBasketServiceServerMockRecorder
	isgomock struct{}
}

// MockBasketServiceServerMockRecorder is the mock recorder for MockBasketServiceServer.
type MockBasketServiceServerMockRecorder struct {
	mock *MockBasketServiceServer
}

// NewMockBasketServiceServer creates a new mock instance.
func NewMockBasketServiceServer(ctrl *gomock.Controller) *MockBasketServiceServer {
	mock := &MockBasketServiceServer{ctrl: ctrl}
	mock.recorder = &MockBasketServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasketServiceServer) EXPECT() *MockBasketServiceServerMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockBasketServiceServer) AddItem(arg0 context.Context, arg1 *AddItemRequest) (*AddItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", arg0, arg1)
	ret0, _ := ret[0].(*AddItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddItem indicates an expected call of AddItem.
func (mr *MockBasketServiceServerMockRecorder) AddItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockBasketServiceServer)(nil).AddItem), arg0, arg1)
}

// CancelBasket mocks base method.
func (m *MockBasketServiceServer) CancelBasket(arg0 context.Context, arg1 *CancelBasketRequest) (*CancelBasketResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBasket", arg0, arg1)
	ret0, _ := ret[0].(*CancelBasketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelBasket indicates an expected call of CancelBasket.
func (mr *MockBasketServiceServerMockRecorder) CancelBasket(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBasket", reflect.TypeOf((*MockBasketServiceServer)(nil).CancelBasket), arg0, arg1)
}

// CheckoutBasket mocks base method.
func (m *MockBasketServiceServer) CheckoutBasket(arg0 context.Context, arg1 *CheckoutBasketRequest) (*CheckoutBasketResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckoutBasket", arg0, arg1)
	ret0, _ := ret[0].(*CheckoutBasketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckoutBasket indicates an expected call of CheckoutBasket.
func (mr *MockBasketServiceServerMockRecorder) CheckoutBasket(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutBasket", reflect.TypeOf((*MockBasketServiceServer)(nil).CheckoutBasket), arg0, arg1)
}

// GetBasket mocks base method.
func (m *MockBasketServiceServer) GetBasket(arg0 context.Context, arg1 *GetBasketRequest) (*GetBasketResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBasket", arg0, arg1)
	ret0, _ := ret[0].(*GetBasketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasket indicates an expected call of GetBasket.
func (mr *MockBasketServiceServerMockRecorder) GetBasket(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasket", reflect.TypeOf((*MockBasketServiceServer)(nil).GetBasket), arg0, arg1)
}

// RemoveItem mocks base method.
func (m *MockBasketServiceServer) RemoveItem(arg0 context.Context, arg1 *RemoveItemRequest) (*RemoveItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", arg0, arg1)
	ret0, _ := ret[0].(*RemoveItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockBasketServiceServerMockRecorder) RemoveItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockBasketServiceServer)(nil).RemoveItem), arg0, arg1)
}

// StartBasket mocks base method.
func (m *MockBasketServiceServer) StartBasket(arg0 context.Context, arg1 *StartBasketRequest) (*StartBasketResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartBasket", arg0, arg1)
	ret0, _ := ret[0].(*StartBasketResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartBasket indicates an expected call of StartBasket.
func (mr *MockBasketServiceServerMockRecorder) StartBasket(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBasket", reflect.TypeOf((*MockBasketServiceServer)(nil).StartBasket), arg0, arg1)
}

// mustEmbedUnimplementedBasketServiceServer mocks base method.
func (m *MockBasketServiceServer) mustEmbedUnimplementedBasketServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedBasketServiceServer")
}

// mustEmbedUnimplementedBasketServiceServer indicates an expected call of mustEmbedUnimplementedBasketServiceServer.
func (mr *MockBasketServiceServerMockRecorder) mustEmbedUnimplementedBasketServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedBasketServiceServer", reflect.TypeOf((*MockBasketServiceServer)(nil).mustEmbedUnimplementedBasketServiceServer))
}
