// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paymentspb/api.proto

package paymentspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizePaymentRequest) Reset() {
	*x = AuthorizePaymentRequest{}
	mi := &file_paymentspb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePaymentRequest) ProtoMessage() {}

func (x *AuthorizePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePaymentRequest.ProtoReflect.Descriptor instead.
func (*AuthorizePaymentRequest) Descriptor() ([]byte, []int) {
	return file_paymentspb_api_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizePaymentRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AuthorizePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AuthorizePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizePaymentResponse) Reset() {
	*x = AuthorizePaymentResponse{}
	mi := &file_paymentspb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePaymentResponse) ProtoMessage() {}

func (x *AuthorizePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePaymentResponse.ProtoReflect.Descriptor instead.
func (*AuthorizePaymentResponse) Descriptor() ([]byte, []int) {
	return file_paymentspb_api_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizePaymentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfirmPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentRequest) Reset() {
	*x = ConfirmPaymentRequest{}
	mi := &file_paymentspb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentRequest) ProtoMessage() {}

func (x *ConfirmPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentRequest) Descriptor() ([]byte, []int) {
	return file_paymentspb_api_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfirmPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentResponse) Reset() {
	*x = ConfirmPaymentResponse{}
	mi := &file_paymentspb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentResponse) ProtoMessage() {}

func (x *ConfirmPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentResponse) Descriptor() ([]byte, []int) {
	return file_paymentspb_api_proto_rawDescGZIP(), []int{3}
}

type CreateInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceRequest) Reset() {
	*x = CreateInvoiceRequest{}
	mi := &file_paymentspb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequest) ProtoMessage() {}

func (x *CreateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_paymentspb_api_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInvoiceRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateInvoiceRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateInvoiceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceResponse) Reset() {
	*x = CreateInvoiceResponse{}
	mi := &file_paymentspb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceResponse) ProtoMessage() {}

func (x *CreateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*CreateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_paymentspb_api_proto_rawDescGZIP(), []int{5}
}

func (x *CreateInvoiceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AdjustInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustInvoiceRequest) Reset() {
	*x = AdjustInvoiceRequest{}
	mi := &file_paymentspb_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustInvoiceRequest) ProtoMessage() {}

func (x *AdjustInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustInvoiceRequest.ProtoReflect.Descriptor instead.
func (*AdjustInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_paymentspb_api_proto_rawDescGZIP(), []int{6}
}

func (x *AdjustInvoiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdjustInvoiceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AdjustInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustInvoiceResponse) Reset() {
	*x = AdjustInvoiceResponse{}
	mi := &file_paymentspb_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustInvoiceResponse) ProtoMessage() {}

func (x *AdjustInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustInvoiceResponse.ProtoReflect.Descriptor instead.
func (*AdjustInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_paymentspb_api_proto_rawDescGZIP(), []int{7}
}

type PayInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayInvoiceRequest) Reset() {
	*x = PayInvoiceRequest{}
	mi := &file_paymentspb_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayInvoiceRequest) ProtoMessage() {}

func (x *PayInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayInvoiceRequest.ProtoReflect.Descriptor instead.
func (*PayInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_paymentspb_api_proto_rawDescGZIP(), []int{8}
}

func (x *PayInvoiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PayInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayInvoiceResponse) Reset() {
	*x = PayInvoiceResponse{}
	mi := &file_paymentspb_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayInvoiceResponse) ProtoMessage() {}

func (x *PayInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayInvoiceResponse.ProtoReflect.Descriptor instead.
func (*PayInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_paymentspb_api_proto_rawDescGZIP(), []int{9}
}

type CancelInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelInvoiceRequest) Reset() {
	*x = CancelInvoiceRequest{}
	mi := &file_paymentspb_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelInvoiceRequest) ProtoMessage() {}

func (x *CancelInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CancelInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_paymentspb_api_proto_rawDescGZIP(), []int{10}
}

func (x *CancelInvoiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelInvoiceResponse) Reset() {
	*x = CancelInvoiceResponse{}
	mi := &file_paymentspb_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelInvoiceResponse) ProtoMessage() {}

func (x *CancelInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelInvoiceResponse.ProtoReflect.Descriptor instead.
func (*CancelInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_paymentspb_api_proto_rawDescGZIP(), []int{11}
}

var File_paymentspb_api_proto protoreflect.FileDescriptor

const file_paymentspb_api_proto_rawDesc = "" +
	"\n" +
	"\x14paymentspb/api.proto\x12\n" +
	"paymentspb\"R\n" +
	"\x17AuthorizePaymentRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"*\n" +
	"\x18AuthorizePaymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15ConfirmPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16ConfirmPaymentResponse\"h\n" +
	"\x14CreateInvoiceRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"'\n" +
	"\x15CreateInvoiceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x14AdjustInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"\x17\n" +
	"\x15AdjustInvoiceResponse\"#\n" +
	"\x11PayInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12PayInvoiceResponse\"&\n" +
	"\x14CancelInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15CancelInvoiceResponse2\xa4\x04\n" +
	"\x0fPaymentsService\x12_\n" +
	"\x10AuthorizePayment\x12#.paymentspb.AuthorizePaymentRequest\x1a$.paymentspb.AuthorizePaymentResponse\"\x00\x12Y\n" +
	"\x0eConfirmPayment\x12!.paymentspb.ConfirmPaymentRequest\x1a\".paymentspb.ConfirmPaymentResponse\"\x00\x12V\n" +
	"\rCreateInvoice\x12 .paymentspb.CreateInvoiceRequest\x1a!.paymentspb.CreateInvoiceResponse\"\x00\x12V\n" +
	"\rAdjustInvoice\x12 .paymentspb.AdjustInvoiceRequest\x1a!.paymentspb.AdjustInvoiceResponse\"\x00\x12M\n" +
	"\n" +
	"PayInvoice\x12\x1d.paymentspb.PayInvoiceRequest\x1a\x1e.paymentspb.PayInvoiceResponse\"\x00\x12V\n" +
	"\rCancelInvoice\x12 .paymentspb.CancelInvoiceRequest\x1a!.paymentspb.CancelInvoiceResponse\"\x00B\x87\x01\n" +
	"\x0ecom.paymentspbB\bApiProtoP\x01Z#mall/payments/paymentspb/paymentspb\xa2\x02\x03PXX\xaa\x02\n" +
	"Paymentspb\xca\x02\n" +
	"Paymentspb\xe2\x02\x16Paymentspb\\GPBMetadata\xea\x02\n" +
	"Paymentspbb\x06proto3"

var (
	file_paymentspb_api_proto_rawDescOnce sync.Once
	file_paymentspb_api_proto_rawDescData []byte
)

func file_paymentspb_api_proto_rawDescGZIP() []byte {
	file_paymentspb_api_proto_rawDescOnce.Do(func() {
		file_paymentspb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentspb_api_proto_rawDesc), len(file_paymentspb_api_proto_rawDesc)))
	})
	return file_paymentspb_api_proto_rawDescData
}

var file_paymentspb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_paymentspb_api_proto_goTypes = []any{
	(*AuthorizePaymentRequest)(nil),  // 0: paymentspb.AuthorizePaymentRequest
	(*AuthorizePaymentResponse)(nil), // 1: paymentspb.AuthorizePaymentResponse
	(*ConfirmPaymentRequest)(nil),    // 2: paymentspb.ConfirmPaymentRequest
	(*ConfirmPaymentResponse)(nil),   // 3: paymentspb.ConfirmPaymentResponse
	(*CreateInvoiceRequest)(nil),     // 4: paymentspb.CreateInvoiceRequest
	(*CreateInvoiceResponse)(nil),    // 5: paymentspb.CreateInvoiceResponse
	(*AdjustInvoiceRequest)(nil),     // 6: paymentspb.AdjustInvoiceRequest
	(*AdjustInvoiceResponse)(nil),    // 7: paymentspb.AdjustInvoiceResponse
	(*PayInvoiceRequest)(nil),        // 8: paymentspb.PayInvoiceRequest
	(*PayInvoiceResponse)(nil),       // 9: paymentspb.PayInvoiceResponse
	(*CancelInvoiceRequest)(nil),     // 10: paymentspb.CancelInvoiceRequest
	(*CancelInvoiceResponse)(nil),    // 11: paymentspb.CancelInvoiceResponse
}
var file_paymentspb_api_proto_depIdxs = []int32{
	0,  // 0: paymentspb.PaymentsService.AuthorizePayment:input_type -> paymentspb.AuthorizePaymentRequest
	2,  // 1: paymentspb.PaymentsService.ConfirmPayment:input_type -> paymentspb.ConfirmPaymentRequest
	4,  // 2: paymentspb.PaymentsService.CreateInvoice:input_type -> paymentspb.CreateInvoiceRequest
	6,  // 3: paymentspb.PaymentsService.AdjustInvoice:input_type -> paymentspb.AdjustInvoiceRequest
	8,  // 4: paymentspb.PaymentsService.PayInvoice:input_type -> paymentspb.PayInvoiceRequest
	10, // 5: paymentspb.PaymentsService.CancelInvoice:input_type -> paymentspb.CancelInvoiceRequest
	1,  // 6: paymentspb.PaymentsService.AuthorizePayment:output_type -> paymentspb.AuthorizePaymentResponse
	3,  // 7: paymentspb.PaymentsService.ConfirmPayment:output_type -> paymentspb.ConfirmPaymentResponse
	5,  // 8: paymentspb.PaymentsService.CreateInvoice:output_type -> paymentspb.CreateInvoiceResponse
	7,  // 9: paymentspb.PaymentsService.AdjustInvoice:output_type -> paymentspb.AdjustInvoiceResponse
	9,  // 10: paymentspb.PaymentsService.PayInvoice:output_type -> paymentspb.PayInvoiceResponse
	11, // 11: paymentspb.PaymentsService.CancelInvoice:output_type -> paymentspb.CancelInvoiceResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_paymentspb_api_proto_init() }
func file_paymentspb_api_proto_init() {
	if File_paymentspb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentspb_api_proto_rawDesc), len(file_paymentspb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paymentspb_api_proto_goTypes,
		DependencyIndexes: file_paymentspb_api_proto_depIdxs,
		MessageInfos:      file_paymentspb_api_proto_msgTypes,
	}.Build()
	File_paymentspb_api_proto = out.File
	file_paymentspb_api_proto_goTypes = nil
	file_paymentspb_api_proto_depIdxs = nil
}
