// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paymentspb/messages.proto

package paymentspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Events
type InvoicePaid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoicePaid) Reset() {
	*x = InvoicePaid{}
	mi := &file_paymentspb_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoicePaid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoicePaid) ProtoMessage() {}

func (x *InvoicePaid) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoicePaid.ProtoReflect.Descriptor instead.
func (*InvoicePaid) Descriptor() ([]byte, []int) {
	return file_paymentspb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *InvoicePaid) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvoicePaid) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// Commands
type ConfirmPayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPayment) Reset() {
	*x = ConfirmPayment{}
	mi := &file_paymentspb_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPayment) ProtoMessage() {}

func (x *ConfirmPayment) ProtoReflect() protoreflect.Message {
	mi := &file_paymentspb_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPayment.ProtoReflect.Descriptor instead.
func (*ConfirmPayment) Descriptor() ([]byte, []int) {
	return file_paymentspb_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmPayment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmPayment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_paymentspb_messages_proto protoreflect.FileDescriptor

const file_paymentspb_messages_proto_rawDesc = "" +
	"\n" +
	"\x19paymentspb/messages.proto\x12\n" +
	"paymentspb\"8\n" +
	"\vInvoicePaid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"8\n" +
	"\x0eConfirmPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amountB\x8c\x01\n" +
	"\x0ecom.paymentspbB\rMessagesProtoP\x01Z#mall/payments/paymentspb/paymentspb\xa2\x02\x03PXX\xaa\x02\n" +
	"Paymentspb\xca\x02\n" +
	"Paymentspb\xe2\x02\x16Paymentspb\\GPBMetadata\xea\x02\n" +
	"Paymentspbb\x06proto3"

var (
	file_paymentspb_messages_proto_rawDescOnce sync.Once
	file_paymentspb_messages_proto_rawDescData []byte
)

func file_paymentspb_messages_proto_rawDescGZIP() []byte {
	file_paymentspb_messages_proto_rawDescOnce.Do(func() {
		file_paymentspb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentspb_messages_proto_rawDesc), len(file_paymentspb_messages_proto_rawDesc)))
	})
	return file_paymentspb_messages_proto_rawDescData
}

var file_paymentspb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_paymentspb_messages_proto_goTypes = []any{
	(*InvoicePaid)(nil),    // 0: paymentspb.InvoicePaid
	(*ConfirmPayment)(nil), // 1: paymentspb.ConfirmPayment
}
var file_paymentspb_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paymentspb_messages_proto_init() }
func file_paymentspb_messages_proto_init() {
	if File_paymentspb_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentspb_messages_proto_rawDesc), len(file_paymentspb_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paymentspb_messages_proto_goTypes,
		DependencyIndexes: file_paymentspb_messages_proto_depIdxs,
		MessageInfos:      file_paymentspb_messages_proto_msgTypes,
	}.Build()
	File_paymentspb_messages_proto = out.File
	file_paymentspb_messages_proto_goTypes = nil
	file_paymentspb_messages_proto_depIdxs = nil
}
