// Code generated by MockGen. DO NOT EDIT.
// Source: mall/payments/paymentspb (interfaces: PaymentsServiceClient,PaymentsServiceServer)
//
// Generated by this command:
//
//	mockgen -destination=paymentspb/mock.go -package=paymentspb mall/payments/paymentspb PaymentsServiceClient,PaymentsServiceServer
//

// Package paymentspb is a generated GoMock package.
package paymentspb

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockPaymentsServiceClient is a mock of PaymentsServiceClient interface.
type MockPaymentsServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentsServiceClientMockRecorder
	isgomock struct{}
}

// MockPaymentsServiceClientMockRecorder is the mock recorder for MockPaymentsServiceClient.
type MockPaymentsServiceClientMockRecorder struct {
	mock *MockPaymentsServiceClient
}

// NewMockPaymentsServiceClient creates a new mock instance.
func NewMockPaymentsServiceClient(ctrl *gomock.Controller) *MockPaymentsServiceClient {
	mock := &MockPaymentsServiceClient{ctrl: ctrl}
	mock.recorder = &MockPaymentsServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentsServiceClient) EXPECT() *MockPaymentsServiceClientMockRecorder {
	return m.recorder
}

// AdjustInvoice mocks base method.
func (m *MockPaymentsServiceClient) AdjustInvoice(ctx context.Context, in *AdjustInvoiceRequest, opts ...grpc.CallOption) (*AdjustInvoiceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdjustInvoice", varargs...)
	ret0, _ := ret[0].(*AdjustInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdjustInvoice indicates an expected call of AdjustInvoice.
func (mr *MockPaymentsServiceClientMockRecorder) AdjustInvoice(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdjustInvoice", reflect.TypeOf((*MockPaymentsServiceClient)(nil).AdjustInvoice), varargs...)
}

// AuthorizePayment mocks base method.
func (m *MockPaymentsServiceClient) AuthorizePayment(ctx context.Context, in *AuthorizePaymentRequest, opts ...grpc.CallOption) (*AuthorizePaymentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AuthorizePayment", varargs...)
	ret0, _ := ret[0].(*AuthorizePaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizePayment indicates an expected call of AuthorizePayment.
func (mr *MockPaymentsServiceClientMockRecorder) AuthorizePayment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizePayment", reflect.TypeOf((*MockPaymentsServiceClient)(nil).AuthorizePayment), varargs...)
}

// CancelInvoice mocks base method.
func (m *MockPaymentsServiceClient) CancelInvoice(ctx context.Context, in *CancelInvoiceRequest, opts ...grpc.CallOption) (*CancelInvoiceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelInvoice", varargs...)
	ret0, _ := ret[0].(*CancelInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelInvoice indicates an expected call of CancelInvoice.
func (mr *MockPaymentsServiceClientMockRecorder) CancelInvoice(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelInvoice", reflect.TypeOf((*MockPaymentsServiceClient)(nil).CancelInvoice), varargs...)
}

// ConfirmPayment mocks base method.
func (m *MockPaymentsServiceClient) ConfirmPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*ConfirmPaymentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ConfirmPayment", varargs...)
	ret0, _ := ret[0].(*ConfirmPaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmPayment indicates an expected call of ConfirmPayment.
func (mr *MockPaymentsServiceClientMockRecorder) ConfirmPayment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmPayment", reflect.TypeOf((*MockPaymentsServiceClient)(nil).ConfirmPayment), varargs...)
}

// CreateInvoice mocks base method.
func (m *MockPaymentsServiceClient) CreateInvoice(ctx context.Context, in *CreateInvoiceRequest, opts ...grpc.CallOption) (*CreateInvoiceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInvoice", varargs...)
	ret0, _ := ret[0].(*CreateInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockPaymentsServiceClientMockRecorder) CreateInvoice(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockPaymentsServiceClient)(nil).CreateInvoice), varargs...)
}

// PayInvoice mocks base method.
func (m *MockPaymentsServiceClient) PayInvoice(ctx context.Context, in *PayInvoiceRequest, opts ...grpc.CallOption) (*PayInvoiceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PayInvoice", varargs...)
	ret0, _ := ret[0].(*PayInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PayInvoice indicates an expected call of PayInvoice.
func (mr *MockPaymentsServiceClientMockRecorder) PayInvoice(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayInvoice", reflect.TypeOf((*MockPaymentsServiceClient)(nil).PayInvoice), varargs...)
}

// MockPaymentsServiceServer is a mock of PaymentsServiceServer interface.
type MockPaymentsServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentsServiceServerMockRecorder
	isgomock struct{}
}

// MockPaymentsServiceServerMockRecorder is the mock recorder for MockPaymentsServiceServer.
type MockPaymentsServiceServerMockRecorder struct {
	mock *MockPaymentsServiceServer
}

// NewMockPaymentsServiceServer creates a new mock instance.
func NewMockPaymentsServiceServer(ctrl *gomock.Controller) *MockPaymentsServiceServer {
	mock := &MockPaymentsServiceServer{ctrl: ctrl}
	mock.recorder = &MockPaymentsServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentsServiceServer) EXPECT() *MockPaymentsServiceServerMockRecorder {
	return m.recorder
}

// AdjustInvoice mocks base method.
func (m *MockPaymentsServiceServer) AdjustInvoice(arg0 context.Context, arg1 *AdjustInvoiceRequest) (*AdjustInvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdjustInvoice", arg0, arg1)
	ret0, _ := ret[0].(*AdjustInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdjustInvoice indicates an expected call of AdjustInvoice.
func (mr *MockPaymentsServiceServerMockRecorder) AdjustInvoice(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdjustInvoice", reflect.TypeOf((*MockPaymentsServiceServer)(nil).AdjustInvoice), arg0, arg1)
}

// AuthorizePayment mocks base method.
func (m *MockPaymentsServiceServer) AuthorizePayment(arg0 context.Context, arg1 *AuthorizePaymentRequest) (*AuthorizePaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizePayment", arg0, arg1)
	ret0, _ := ret[0].(*AuthorizePaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizePayment indicates an expected call of AuthorizePayment.
func (mr *MockPaymentsServiceServerMockRecorder) AuthorizePayment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizePayment", reflect.TypeOf((*MockPaymentsServiceServer)(nil).AuthorizePayment), arg0, arg1)
}

// CancelInvoice mocks base method.
func (m *MockPaymentsServiceServer) CancelInvoice(arg0 context.Context, arg1 *CancelInvoiceRequest) (*CancelInvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelInvoice", arg0, arg1)
	ret0, _ := ret[0].(*CancelInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelInvoice indicates an expected call of CancelInvoice.
func (mr *MockPaymentsServiceServerMockRecorder) CancelInvoice(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelInvoice", reflect.TypeOf((*MockPaymentsServiceServer)(nil).CancelInvoice), arg0, arg1)
}

// ConfirmPayment mocks base method.
func (m *MockPaymentsServiceServer) ConfirmPayment(arg0 context.Context, arg1 *ConfirmPaymentRequest) (*ConfirmPaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmPayment", arg0, arg1)
	ret0, _ := ret[0].(*ConfirmPaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmPayment indicates an expected call of ConfirmPayment.
func (mr *MockPaymentsServiceServerMockRecorder) ConfirmPayment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmPayment", reflect.TypeOf((*MockPaymentsServiceServer)(nil).ConfirmPayment), arg0, arg1)
}

// CreateInvoice mocks base method.
func (m *MockPaymentsServiceServer) CreateInvoice(arg0 context.Context, arg1 *CreateInvoiceRequest) (*CreateInvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", arg0, arg1)
	ret0, _ := ret[0].(*CreateInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockPaymentsServiceServerMockRecorder) CreateInvoice(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockPaymentsServiceServer)(nil).CreateInvoice), arg0, arg1)
}

// PayInvoice mocks base method.
func (m *MockPaymentsServiceServer) PayInvoice(arg0 context.Context, arg1 *PayInvoiceRequest) (*PayInvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PayInvoice", arg0, arg1)
	ret0, _ := ret[0].(*PayInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PayInvoice indicates an expected call of PayInvoice.
func (mr *MockPaymentsServiceServerMockRecorder) PayInvoice(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayInvoice", reflect.TypeOf((*MockPaymentsServiceServer)(nil).PayInvoice), arg0, arg1)
}

// mustEmbedUnimplementedPaymentsServiceServer mocks base method.
func (m *MockPaymentsServiceServer) mustEmbedUnimplementedPaymentsServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedPaymentsServiceServer")
}

// mustEmbedUnimplementedPaymentsServiceServer indicates an expected call of mustEmbedUnimplementedPaymentsServiceServer.
func (mr *MockPaymentsServiceServerMockRecorder) mustEmbedUnimplementedPaymentsServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedPaymentsServiceServer", reflect.TypeOf((*MockPaymentsServiceServer)(nil).mustEmbedUnimplementedPaymentsServiceServer))
}
