// Code generated by MockGen. DO NOT EDIT.
// Source: mall/ordering/internal/domain (interfaces: CustomerRepository,InvoiceRepository,NotificationRepository,OrderRepository,PaymentRepository,ShoppingRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/domain/mock.go -package=domain mall/ordering/internal/domain CustomerRepository,InvoiceRepository,NotificationRepository,OrderRepository,PaymentRepository,ShoppingRepository
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCustomerRepository is a mock of CustomerRepository interface.
type MockCustomerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerRepositoryMockRecorder is the mock recorder for MockCustomerRepository.
type MockCustomerRepositoryMockRecorder struct {
	mock *MockCustomerRepository
}

// NewMockCustomerRepository creates a new mock instance.
func NewMockCustomerRepository(ctrl *gomock.Controller) *MockCustomerRepository {
	mock := &MockCustomerRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerRepository) EXPECT() *MockCustomerRepositoryMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockCustomerRepository) Authorize(ctx context.Context, customerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, customerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Authorize indicates an expected call of Authorize.
func (mr *MockCustomerRepositoryMockRecorder) Authorize(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockCustomerRepository)(nil).Authorize), ctx, customerID)
}

// MockInvoiceRepository is a mock of InvoiceRepository interface.
type MockInvoiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceRepositoryMockRecorder
	isgomock struct{}
}

// MockInvoiceRepositoryMockRecorder is the mock recorder for MockInvoiceRepository.
type MockInvoiceRepositoryMockRecorder struct {
	mock *MockInvoiceRepository
}

// NewMockInvoiceRepository creates a new mock instance.
func NewMockInvoiceRepository(ctrl *gomock.Controller) *MockInvoiceRepository {
	mock := &MockInvoiceRepository{ctrl: ctrl}
	mock.recorder = &MockInvoiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceRepository) EXPECT() *MockInvoiceRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockInvoiceRepository) Delete(ctx context.Context, invoiceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, invoiceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInvoiceRepositoryMockRecorder) Delete(ctx, invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInvoiceRepository)(nil).Delete), ctx, invoiceID)
}

// Save mocks base method.
func (m *MockInvoiceRepository) Save(ctx context.Context, orderID, paymentID string, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, orderID, paymentID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockInvoiceRepositoryMockRecorder) Save(ctx, orderID, paymentID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockInvoiceRepository)(nil).Save), ctx, orderID, paymentID, amount)
}

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// NotifyOrderCanceled mocks base method.
func (m *MockNotificationRepository) NotifyOrderCanceled(ctx context.Context, orderID, customerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyOrderCanceled", ctx, orderID, customerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyOrderCanceled indicates an expected call of NotifyOrderCanceled.
func (mr *MockNotificationRepositoryMockRecorder) NotifyOrderCanceled(ctx, orderID, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderCanceled", reflect.TypeOf((*MockNotificationRepository)(nil).NotifyOrderCanceled), ctx, orderID, customerID)
}

// NotifyOrderCreated mocks base method.
func (m *MockNotificationRepository) NotifyOrderCreated(ctx context.Context, orderID, customerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyOrderCreated", ctx, orderID, customerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyOrderCreated indicates an expected call of NotifyOrderCreated.
func (mr *MockNotificationRepositoryMockRecorder) NotifyOrderCreated(ctx, orderID, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderCreated", reflect.TypeOf((*MockNotificationRepository)(nil).NotifyOrderCreated), ctx, orderID, customerID)
}

// NotifyOrderReady mocks base method.
func (m *MockNotificationRepository) NotifyOrderReady(ctx context.Context, orderID, customerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyOrderReady", ctx, orderID, customerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyOrderReady indicates an expected call of NotifyOrderReady.
func (mr *MockNotificationRepositoryMockRecorder) NotifyOrderReady(ctx, orderID, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderReady", reflect.TypeOf((*MockNotificationRepository)(nil).NotifyOrderReady), ctx, orderID, customerID)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockOrderRepository) Load(ctx context.Context, orderID string) (*Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, orderID)
	ret0, _ := ret[0].(*Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockOrderRepositoryMockRecorder) Load(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockOrderRepository)(nil).Load), ctx, orderID)
}

// Save mocks base method.
func (m *MockOrderRepository) Save(ctx context.Context, order *Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockOrderRepositoryMockRecorder) Save(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockOrderRepository)(nil).Save), ctx, order)
}

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// Confirm mocks base method.
func (m *MockPaymentRepository) Confirm(ctx context.Context, paymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Confirm indicates an expected call of Confirm.
func (mr *MockPaymentRepositoryMockRecorder) Confirm(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockPaymentRepository)(nil).Confirm), ctx, paymentID)
}

// MockShoppingRepository is a mock of ShoppingRepository interface.
type MockShoppingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShoppingRepositoryMockRecorder
	isgomock struct{}
}

// MockShoppingRepositoryMockRecorder is the mock recorder for MockShoppingRepository.
type MockShoppingRepositoryMockRecorder struct {
	mock *MockShoppingRepository
}

// NewMockShoppingRepository creates a new mock instance.
func NewMockShoppingRepository(ctrl *gomock.Controller) *MockShoppingRepository {
	mock := &MockShoppingRepository{ctrl: ctrl}
	mock.recorder = &MockShoppingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShoppingRepository) EXPECT() *MockShoppingRepositoryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockShoppingRepository) Cancel(ctx context.Context, shoppingID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, shoppingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockShoppingRepositoryMockRecorder) Cancel(ctx, shoppingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockShoppingRepository)(nil).Cancel), ctx, shoppingID)
}

// Create mocks base method.
func (m *MockShoppingRepository) Create(ctx context.Context, orderID string, items []Item) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orderID, items)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockShoppingRepositoryMockRecorder) Create(ctx, orderID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShoppingRepository)(nil).Create), ctx, orderID, items)
}
