// Code generated by MockGen. DO NOT EDIT.
// Source: mall/customers/internal/application (interfaces: App)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mock.go -package=application mall/customers/internal/application App
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	domain "mall/customers/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// AuthorizeCustomer mocks base method.
func (m *MockApp) AuthorizeCustomer(ctx context.Context, authorize AuthorizeCustomer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeCustomer", ctx, authorize)
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthorizeCustomer indicates an expected call of AuthorizeCustomer.
func (mr *MockAppMockRecorder) AuthorizeCustomer(ctx, authorize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeCustomer", reflect.TypeOf((*MockApp)(nil).AuthorizeCustomer), ctx, authorize)
}

// DisableCustomer mocks base method.
func (m *MockApp) DisableCustomer(ctx context.Context, disable DisableCustomer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableCustomer", ctx, disable)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableCustomer indicates an expected call of DisableCustomer.
func (mr *MockAppMockRecorder) DisableCustomer(ctx, disable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableCustomer", reflect.TypeOf((*MockApp)(nil).DisableCustomer), ctx, disable)
}

// EnableCustomer mocks base method.
func (m *MockApp) EnableCustomer(ctx context.Context, enable EnableCustomer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableCustomer", ctx, enable)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableCustomer indicates an expected call of EnableCustomer.
func (mr *MockAppMockRecorder) EnableCustomer(ctx, enable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableCustomer", reflect.TypeOf((*MockApp)(nil).EnableCustomer), ctx, enable)
}

// GetCustomer mocks base method.
func (m *MockApp) GetCustomer(ctx context.Context, get GetCustomer) (*domain.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomer", ctx, get)
	ret0, _ := ret[0].(*domain.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomer indicates an expected call of GetCustomer.
func (mr *MockAppMockRecorder) GetCustomer(ctx, get any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomer", reflect.TypeOf((*MockApp)(nil).GetCustomer), ctx, get)
}

// RegisterCustomer mocks base method.
func (m *MockApp) RegisterCustomer(ctx context.Context, register RegisterCustomer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterCustomer", ctx, register)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterCustomer indicates an expected call of RegisterCustomer.
func (mr *MockAppMockRecorder) RegisterCustomer(ctx, register any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCustomer", reflect.TypeOf((*MockApp)(nil).RegisterCustomer), ctx, register)
}
