// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: customerspb/api.proto

package customerspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SmsNumber     string                 `protobuf:"bytes,2,opt,name=sms_number,json=smsNumber,proto3" json:"sms_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCustomerRequest) Reset() {
	*x = RegisterCustomerRequest{}
	mi := &file_customerspb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCustomerRequest) ProtoMessage() {}

func (x *RegisterCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customerspb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCustomerRequest.ProtoReflect.Descriptor instead.
func (*RegisterCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customerspb_api_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterCustomerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterCustomerRequest) GetSmsNumber() string {
	if x != nil {
		return x.SmsNumber
	}
	return ""
}

type RegisterCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCustomerResponse) Reset() {
	*x = RegisterCustomerResponse{}
	mi := &file_customerspb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCustomerResponse) ProtoMessage() {}

func (x *RegisterCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customerspb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCustomerResponse.ProtoReflect.Descriptor instead.
func (*RegisterCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customerspb_api_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterCustomerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuthorizeCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeCustomerRequest) Reset() {
	*x = AuthorizeCustomerRequest{}
	mi := &file_customerspb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeCustomerRequest) ProtoMessage() {}

func (x *AuthorizeCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customerspb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeCustomerRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customerspb_api_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeCustomerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuthorizeCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeCustomerResponse) Reset() {
	*x = AuthorizeCustomerResponse{}
	mi := &file_customerspb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeCustomerResponse) ProtoMessage() {}

func (x *AuthorizeCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customerspb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeCustomerResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customerspb_api_proto_rawDescGZIP(), []int{3}
}

type GetCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_customerspb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customerspb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customerspb_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetCustomerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerResponse) Reset() {
	*x = GetCustomerResponse{}
	mi := &file_customerspb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerResponse) ProtoMessage() {}

func (x *GetCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customerspb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customerspb_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type EnableCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableCustomerRequest) Reset() {
	*x = EnableCustomerRequest{}
	mi := &file_customerspb_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableCustomerRequest) ProtoMessage() {}

func (x *EnableCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customerspb_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableCustomerRequest.ProtoReflect.Descriptor instead.
func (*EnableCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customerspb_api_proto_rawDescGZIP(), []int{6}
}

func (x *EnableCustomerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EnableCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableCustomerResponse) Reset() {
	*x = EnableCustomerResponse{}
	mi := &file_customerspb_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableCustomerResponse) ProtoMessage() {}

func (x *EnableCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customerspb_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableCustomerResponse.ProtoReflect.Descriptor instead.
func (*EnableCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customerspb_api_proto_rawDescGZIP(), []int{7}
}

type DisableCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableCustomerRequest) Reset() {
	*x = DisableCustomerRequest{}
	mi := &file_customerspb_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableCustomerRequest) ProtoMessage() {}

func (x *DisableCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customerspb_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableCustomerRequest.ProtoReflect.Descriptor instead.
func (*DisableCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customerspb_api_proto_rawDescGZIP(), []int{8}
}

func (x *DisableCustomerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DisableCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableCustomerResponse) Reset() {
	*x = DisableCustomerResponse{}
	mi := &file_customerspb_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableCustomerResponse) ProtoMessage() {}

func (x *DisableCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customerspb_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableCustomerResponse.ProtoReflect.Descriptor instead.
func (*DisableCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customerspb_api_proto_rawDescGZIP(), []int{9}
}

var File_customerspb_api_proto protoreflect.FileDescriptor

const file_customerspb_api_proto_rawDesc = "" +
	"\n" +
	"\x15customerspb/api.proto\x12\vcustomerspb\x1a\x1acustomerspb/messages.proto\"L\n" +
	"\x17RegisterCustomerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sms_number\x18\x02 \x01(\tR\tsmsNumber\"*\n" +
	"\x18RegisterCustomerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x18AuthorizeCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19AuthorizeCustomerResponse\"$\n" +
	"\x12GetCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x13GetCustomerResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customerspb.CustomerR\bcustomer\"'\n" +
	"\x15EnableCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16EnableCustomerResponse\"(\n" +
	"\x16DisableCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17DisableCustomerResponse2\xec\x03\n" +
	"\x10CustomersService\x12a\n" +
	"\x10RegisterCustomer\x12$.customerspb.RegisterCustomerRequest\x1a%.customerspb.RegisterCustomerResponse\"\x00\x12d\n" +
	"\x11AuthorizeCustomer\x12%.customerspb.AuthorizeCustomerRequest\x1a&.customerspb.AuthorizeCustomerResponse\"\x00\x12R\n" +
	"\vGetCustomer\x12\x1f.customerspb.GetCustomerRequest\x1a .customerspb.GetCustomerResponse\"\x00\x12[\n" +
	"\x0eEnableCustomer\x12\".customerspb.EnableCustomerRequest\x1a#.customerspb.EnableCustomerResponse\"\x00\x12^\n" +
	"\x0fDisableCustomer\x12#.customerspb.DisableCustomerRequest\x1a$.customerspb.DisableCustomerResponse\"\x00B\x8f\x01\n" +
	"\x0fcom.customerspbB\bApiProtoP\x01Z&mall/customers/customerspb/customerspb\xa2\x02\x03CXX\xaa\x02\vCustomerspb\xca\x02\vCustomerspb\xe2\x02\x17Customerspb\\GPBMetadata\xea\x02\vCustomerspbb\x06proto3"

var (
	file_customerspb_api_proto_rawDescOnce sync.Once
	file_customerspb_api_proto_rawDescData []byte
)

func file_customerspb_api_proto_rawDescGZIP() []byte {
	file_customerspb_api_proto_rawDescOnce.Do(func() {
		file_customerspb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customerspb_api_proto_rawDesc), len(file_customerspb_api_proto_rawDesc)))
	})
	return file_customerspb_api_proto_rawDescData
}

var file_customerspb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_customerspb_api_proto_goTypes = []any{
	(*RegisterCustomerRequest)(nil),   // 0: customerspb.RegisterCustomerRequest
	(*RegisterCustomerResponse)(nil),  // 1: customerspb.RegisterCustomerResponse
	(*AuthorizeCustomerRequest)(nil),  // 2: customerspb.AuthorizeCustomerRequest
	(*AuthorizeCustomerResponse)(nil), // 3: customerspb.AuthorizeCustomerResponse
	(*GetCustomerRequest)(nil),        // 4: customerspb.GetCustomerRequest
	(*GetCustomerResponse)(nil),       // 5: customerspb.GetCustomerResponse
	(*EnableCustomerRequest)(nil),     // 6: customerspb.EnableCustomerRequest
	(*EnableCustomerResponse)(nil),    // 7: customerspb.EnableCustomerResponse
	(*DisableCustomerRequest)(nil),    // 8: customerspb.DisableCustomerRequest
	(*DisableCustomerResponse)(nil),   // 9: customerspb.DisableCustomerResponse
	(*Customer)(nil),                  // 10: customerspb.Customer
}
var file_customerspb_api_proto_depIdxs = []int32{
	10, // 0: customerspb.GetCustomerResponse.customer:type_name -> customerspb.Customer
	0,  // 1: customerspb.CustomersService.RegisterCustomer:input_type -> customerspb.RegisterCustomerRequest
	2,  // 2: customerspb.CustomersService.AuthorizeCustomer:input_type -> customerspb.AuthorizeCustomerRequest
	4,  // 3: customerspb.CustomersService.GetCustomer:input_type -> customerspb.GetCustomerRequest
	6,  // 4: customerspb.CustomersService.EnableCustomer:input_type -> customerspb.EnableCustomerRequest
	8,  // 5: customerspb.CustomersService.DisableCustomer:input_type -> customerspb.DisableCustomerRequest
	1,  // 6: customerspb.CustomersService.RegisterCustomer:output_type -> customerspb.RegisterCustomerResponse
	3,  // 7: customerspb.CustomersService.AuthorizeCustomer:output_type -> customerspb.AuthorizeCustomerResponse
	5,  // 8: customerspb.CustomersService.GetCustomer:output_type -> customerspb.GetCustomerResponse
	7,  // 9: customerspb.CustomersService.EnableCustomer:output_type -> customerspb.EnableCustomerResponse
	9,  // 10: customerspb.CustomersService.DisableCustomer:output_type -> customerspb.DisableCustomerResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_customerspb_api_proto_init() }
func file_customerspb_api_proto_init() {
	if File_customerspb_api_proto != nil {
		return
	}
	file_customerspb_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customerspb_api_proto_rawDesc), len(file_customerspb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customerspb_api_proto_goTypes,
		DependencyIndexes: file_customerspb_api_proto_depIdxs,
		MessageInfos:      file_customerspb_api_proto_msgTypes,
	}.Build()
	File_customerspb_api_proto = out.File
	file_customerspb_api_proto_goTypes = nil
	file_customerspb_api_proto_depIdxs = nil
}
