// Code generated by MockGen. DO NOT EDIT.
// Source: mall/customers/customerspb (interfaces: CustomersServiceClient,CustomersServiceServer)
//
// Generated by this command:
//
//	mockgen -destination=customerspb/mock.go -package=customerspb mall/customers/customerspb CustomersServiceClient,CustomersServiceServer
//

// Package customerspb is a generated GoMock package.
package customerspb

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCustomersServiceClient is a mock of CustomersServiceClient interface.
type MockCustomersServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCustomersServiceClientMockRecorder
	isgomock struct{}
}

// MockCustomersServiceClientMockRecorder is the mock recorder for MockCustomersServiceClient.
type MockCustomersServiceClientMockRecorder struct {
	mock *MockCustomersServiceClient
}

// NewMockCustomersServiceClient creates a new mock instance.
func NewMockCustomersServiceClient(ctrl *gomock.Controller) *MockCustomersServiceClient {
	mock := &MockCustomersServiceClient{ctrl: ctrl}
	mock.recorder = &MockCustomersServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomersServiceClient) EXPECT() *MockCustomersServiceClientMockRecorder {
	return m.recorder
}

// AuthorizeCustomer mocks base method.
func (m *MockCustomersServiceClient) AuthorizeCustomer(ctx context.Context, in *AuthorizeCustomerRequest, opts ...grpc.CallOption) (*AuthorizeCustomerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AuthorizeCustomer", varargs...)
	ret0, _ := ret[0].(*AuthorizeCustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizeCustomer indicates an expected call of AuthorizeCustomer.
func (mr *MockCustomersServiceClientMockRecorder) AuthorizeCustomer(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeCustomer", reflect.TypeOf((*MockCustomersServiceClient)(nil).AuthorizeCustomer), varargs...)
}

// DisableCustomer mocks base method.
func (m *MockCustomersServiceClient) DisableCustomer(ctx context.Context, in *DisableCustomerRequest, opts ...grpc.CallOption) (*DisableCustomerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DisableCustomer", varargs...)
	ret0, _ := ret[0].(*DisableCustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableCustomer indicates an expected call of DisableCustomer.
func (mr *MockCustomersServiceClientMockRecorder) DisableCustomer(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableCustomer", reflect.TypeOf((*MockCustomersServiceClient)(nil).DisableCustomer), varargs...)
}

// EnableCustomer mocks base method.
func (m *MockCustomersServiceClient) EnableCustomer(ctx context.Context, in *EnableCustomerRequest, opts ...grpc.CallOption) (*EnableCustomerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EnableCustomer", varargs...)
	ret0, _ := ret[0].(*EnableCustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableCustomer indicates an expected call of EnableCustomer.
func (mr *MockCustomersServiceClientMockRecorder) EnableCustomer(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableCustomer", reflect.TypeOf((*MockCustomersServiceClient)(nil).EnableCustomer), varargs...)
}

// GetCustomer mocks base method.
func (m *MockCustomersServiceClient) GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*GetCustomerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCustomer", varargs...)
	ret0, _ := ret[0].(*GetCustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomer indicates an expected call of GetCustomer.
func (mr *MockCustomersServiceClientMockRecorder) GetCustomer(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomer", reflect.TypeOf((*MockCustomersServiceClient)(nil).GetCustomer), varargs...)
}

// RegisterCustomer mocks base method.
func (m *MockCustomersServiceClient) RegisterCustomer(ctx context.Context, in *RegisterCustomerRequest, opts ...grpc.CallOption) (*RegisterCustomerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterCustomer", varargs...)
	ret0, _ := ret[0].(*RegisterCustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterCustomer indicates an expected call of RegisterCustomer.
func (mr *MockCustomersServiceClientMockRecorder) RegisterCustomer(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCustomer", reflect.TypeOf((*MockCustomersServiceClient)(nil).RegisterCustomer), varargs...)
}

// MockCustomersServiceServer is a mock of CustomersServiceServer interface.
type MockCustomersServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockCustomersServiceServerMockRecorder
	isgomock struct{}
}

// MockCustomersServiceServerMockRecorder is the mock recorder for MockCustomersServiceServer.
type MockCustomersServiceServerMockRecorder struct {
	mock *MockCustomersServiceServer
}

// NewMockCustomersServiceServer creates a new mock instance.
func NewMockCustomersServiceServer(ctrl *gomock.Controller) *MockCustomersServiceServer {
	mock := &MockCustomersServiceServer{ctrl: ctrl}
	mock.recorder = &MockCustomersServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomersServiceServer) EXPECT() *MockCustomersServiceServerMockRecorder {
	return m.recorder
}

// AuthorizeCustomer mocks base method.
func (m *MockCustomersServiceServer) AuthorizeCustomer(arg0 context.Context, arg1 *AuthorizeCustomerRequest) (*AuthorizeCustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeCustomer", arg0, arg1)
	ret0, _ := ret[0].(*AuthorizeCustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizeCustomer indicates an expected call of AuthorizeCustomer.
func (mr *MockCustomersServiceServerMockRecorder) AuthorizeCustomer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeCustomer", reflect.TypeOf((*MockCustomersServiceServer)(nil).AuthorizeCustomer), arg0, arg1)
}

// DisableCustomer mocks base method.
func (m *MockCustomersServiceServer) DisableCustomer(arg0 context.Context, arg1 *DisableCustomerRequest) (*DisableCustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableCustomer", arg0, arg1)
	ret0, _ := ret[0].(*DisableCustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableCustomer indicates an expected call of DisableCustomer.
func (mr *MockCustomersServiceServerMockRecorder) DisableCustomer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableCustomer", reflect.TypeOf((*MockCustomersServiceServer)(nil).DisableCustomer), arg0, arg1)
}

// EnableCustomer mocks base method.
func (m *MockCustomersServiceServer) EnableCustomer(arg0 context.Context, arg1 *EnableCustomerRequest) (*EnableCustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableCustomer", arg0, arg1)
	ret0, _ := ret[0].(*EnableCustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableCustomer indicates an expected call of EnableCustomer.
func (mr *MockCustomersServiceServerMockRecorder) EnableCustomer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableCustomer", reflect.TypeOf((*MockCustomersServiceServer)(nil).EnableCustomer), arg0, arg1)
}

// GetCustomer mocks base method.
func (m *MockCustomersServiceServer) GetCustomer(arg0 context.Context, arg1 *GetCustomerRequest) (*GetCustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomer", arg0, arg1)
	ret0, _ := ret[0].(*GetCustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomer indicates an expected call of GetCustomer.
func (mr *MockCustomersServiceServerMockRecorder) GetCustomer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomer", reflect.TypeOf((*MockCustomersServiceServer)(nil).GetCustomer), arg0, arg1)
}

// RegisterCustomer mocks base method.
func (m *MockCustomersServiceServer) RegisterCustomer(arg0 context.Context, arg1 *RegisterCustomerRequest) (*RegisterCustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterCustomer", arg0, arg1)
	ret0, _ := ret[0].(*RegisterCustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterCustomer indicates an expected call of RegisterCustomer.
func (mr *MockCustomersServiceServerMockRecorder) RegisterCustomer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCustomer", reflect.TypeOf((*MockCustomersServiceServer)(nil).RegisterCustomer), arg0, arg1)
}

// mustEmbedUnimplementedCustomersServiceServer mocks base method.
func (m *MockCustomersServiceServer) mustEmbedUnimplementedCustomersServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCustomersServiceServer")
}

// mustEmbedUnimplementedCustomersServiceServer indicates an expected call of mustEmbedUnimplementedCustomersServiceServer.
func (mr *MockCustomersServiceServerMockRecorder) mustEmbedUnimplementedCustomersServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCustomersServiceServer", reflect.TypeOf((*MockCustomersServiceServer)(nil).mustEmbedUnimplementedCustomersServiceServer))
}
