// Code generated by MockGen. DO NOT EDIT.
// Source: mall/search/searchpb (interfaces: SearchServiceClient,SearchServiceServer)
//
// Generated by this command:
//
//	mockgen -destination=searchpb/mock.go -package=searchpb mall/search/searchpb SearchServiceClient,SearchServiceServer
//

// Package searchpb is a generated GoMock package.
package searchpb

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockSearchServiceClient is a mock of SearchServiceClient interface.
type MockSearchServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockSearchServiceClientMockRecorder
	isgomock struct{}
}

// MockSearchServiceClientMockRecorder is the mock recorder for MockSearchServiceClient.
type MockSearchServiceClientMockRecorder struct {
	mock *MockSearchServiceClient
}

// NewMockSearchServiceClient creates a new mock instance.
func NewMockSearchServiceClient(ctrl *gomock.Controller) *MockSearchServiceClient {
	mock := &MockSearchServiceClient{ctrl: ctrl}
	mock.recorder = &MockSearchServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchServiceClient) EXPECT() *MockSearchServiceClientMockRecorder {
	return m.recorder
}

// GetOrder mocks base method.
func (m *MockSearchServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrder", varargs...)
	ret0, _ := ret[0].(*GetOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockSearchServiceClientMockRecorder) GetOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockSearchServiceClient)(nil).GetOrder), varargs...)
}

// SearchOrders mocks base method.
func (m *MockSearchServiceClient) SearchOrders(ctx context.Context, in *SearchOrdersRequest, opts ...grpc.CallOption) (*SearchOrdersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchOrders", varargs...)
	ret0, _ := ret[0].(*SearchOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchOrders indicates an expected call of SearchOrders.
func (mr *MockSearchServiceClientMockRecorder) SearchOrders(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchOrders", reflect.TypeOf((*MockSearchServiceClient)(nil).SearchOrders), varargs...)
}

// MockSearchServiceServer is a mock of SearchServiceServer interface.
type MockSearchServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockSearchServiceServerMockRecorder
	isgomock struct{}
}

// MockSearchServiceServerMockRecorder is the mock recorder for MockSearchServiceServer.
type MockSearchServiceServerMockRecorder struct {
	mock *MockSearchServiceServer
}

// NewMockSearchServiceServer creates a new mock instance.
func NewMockSearchServiceServer(ctrl *gomock.Controller) *MockSearchServiceServer {
	mock := &MockSearchServiceServer{ctrl: ctrl}
	mock.recorder = &MockSearchServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchServiceServer) EXPECT() *MockSearchServiceServerMockRecorder {
	return m.recorder
}

// GetOrder mocks base method.
func (m *MockSearchServiceServer) GetOrder(arg0 context.Context, arg1 *GetOrderRequest) (*GetOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", arg0, arg1)
	ret0, _ := ret[0].(*GetOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockSearchServiceServerMockRecorder) GetOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockSearchServiceServer)(nil).GetOrder), arg0, arg1)
}

// SearchOrders mocks base method.
func (m *MockSearchServiceServer) SearchOrders(arg0 context.Context, arg1 *SearchOrdersRequest) (*SearchOrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchOrders", arg0, arg1)
	ret0, _ := ret[0].(*SearchOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchOrders indicates an expected call of SearchOrders.
func (mr *MockSearchServiceServerMockRecorder) SearchOrders(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchOrders", reflect.TypeOf((*MockSearchServiceServer)(nil).SearchOrders), arg0, arg1)
}

// mustEmbedUnimplementedSearchServiceServer mocks base method.
func (m *MockSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSearchServiceServer")
}

// mustEmbedUnimplementedSearchServiceServer indicates an expected call of mustEmbedUnimplementedSearchServiceServer.
func (mr *MockSearchServiceServerMockRecorder) mustEmbedUnimplementedSearchServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSearchServiceServer", reflect.TypeOf((*MockSearchServiceServer)(nil).mustEmbedUnimplementedSearchServiceServer))
}
