// Code generated by MockGen. DO NOT EDIT.
// Source: mall/notifications/internal/application (interfaces: App)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mock.go -package=application mall/notifications/internal/application App
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// NotifyOrderCanceled mocks base method.
func (m *MockApp) NotifyOrderCanceled(ctx context.Context, notify OrderCanceled) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyOrderCanceled", ctx, notify)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyOrderCanceled indicates an expected call of NotifyOrderCanceled.
func (mr *MockAppMockRecorder) NotifyOrderCanceled(ctx, notify any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderCanceled", reflect.TypeOf((*MockApp)(nil).NotifyOrderCanceled), ctx, notify)
}

// NotifyOrderCreated mocks base method.
func (m *MockApp) NotifyOrderCreated(ctx context.Context, notify OrderCreated) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyOrderCreated", ctx, notify)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyOrderCreated indicates an expected call of NotifyOrderCreated.
func (mr *MockAppMockRecorder) NotifyOrderCreated(ctx, notify any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderCreated", reflect.TypeOf((*MockApp)(nil).NotifyOrderCreated), ctx, notify)
}

// NotifyOrderReady mocks base method.
func (m *MockApp) NotifyOrderReady(ctx context.Context, notify OrderReady) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyOrderReady", ctx, notify)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyOrderReady indicates an expected call of NotifyOrderReady.
func (mr *MockAppMockRecorder) NotifyOrderReady(ctx, notify any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderReady", reflect.TypeOf((*MockApp)(nil).NotifyOrderReady), ctx, notify)
}
