// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notificationspb/api.proto

package notificationspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyOrderCreatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOrderCreatedRequest) Reset() {
	*x = NotifyOrderCreatedRequest{}
	mi := &file_notificationspb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOrderCreatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOrderCreatedRequest) ProtoMessage() {}

func (x *NotifyOrderCreatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOrderCreatedRequest.ProtoReflect.Descriptor instead.
func (*NotifyOrderCreatedRequest) Descriptor() ([]byte, []int) {
	return file_notificationspb_api_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyOrderCreatedRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *NotifyOrderCreatedRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type NotifyOrderCreatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOrderCreatedResponse) Reset() {
	*x = NotifyOrderCreatedResponse{}
	mi := &file_notificationspb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOrderCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOrderCreatedResponse) ProtoMessage() {}

func (x *NotifyOrderCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOrderCreatedResponse.ProtoReflect.Descriptor instead.
func (*NotifyOrderCreatedResponse) Descriptor() ([]byte, []int) {
	return file_notificationspb_api_proto_rawDescGZIP(), []int{1}
}

type NotifyOrderCanceledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOrderCanceledRequest) Reset() {
	*x = NotifyOrderCanceledRequest{}
	mi := &file_notificationspb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOrderCanceledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOrderCanceledRequest) ProtoMessage() {}

func (x *NotifyOrderCanceledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOrderCanceledRequest.ProtoReflect.Descriptor instead.
func (*NotifyOrderCanceledRequest) Descriptor() ([]byte, []int) {
	return file_notificationspb_api_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyOrderCanceledRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *NotifyOrderCanceledRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type NotifyOrderCanceledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOrderCanceledResponse) Reset() {
	*x = NotifyOrderCanceledResponse{}
	mi := &file_notificationspb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOrderCanceledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOrderCanceledResponse) ProtoMessage() {}

func (x *NotifyOrderCanceledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOrderCanceledResponse.ProtoReflect.Descriptor instead.
func (*NotifyOrderCanceledResponse) Descriptor() ([]byte, []int) {
	return file_notificationspb_api_proto_rawDescGZIP(), []int{3}
}

type NotifyOrderReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOrderReadyRequest) Reset() {
	*x = NotifyOrderReadyRequest{}
	mi := &file_notificationspb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOrderReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOrderReadyRequest) ProtoMessage() {}

func (x *NotifyOrderReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOrderReadyRequest.ProtoReflect.Descriptor instead.
func (*NotifyOrderReadyRequest) Descriptor() ([]byte, []int) {
	return file_notificationspb_api_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyOrderReadyRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *NotifyOrderReadyRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type NotifyOrderReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOrderReadyResponse) Reset() {
	*x = NotifyOrderReadyResponse{}
	mi := &file_notificationspb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOrderReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOrderReadyResponse) ProtoMessage() {}

func (x *NotifyOrderReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOrderReadyResponse.ProtoReflect.Descriptor instead.
func (*NotifyOrderReadyResponse) Descriptor() ([]byte, []int) {
	return file_notificationspb_api_proto_rawDescGZIP(), []int{5}
}

var File_notificationspb_api_proto protoreflect.FileDescriptor

const file_notificationspb_api_proto_rawDesc = "" +
	"\n" +
	"\x19notificationspb/api.proto\x12\x0fnotificationspb\"W\n" +
	"\x19NotifyOrderCreatedRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\"\x1c\n" +
	"\x1aNotifyOrderCreatedResponse\"X\n" +
	"\x1aNotifyOrderCanceledRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\"\x1d\n" +
	"\x1bNotifyOrderCanceledResponse\"U\n" +
	"\x17NotifyOrderReadyRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\"\x1a\n" +
	"\x18NotifyOrderReadyResponse2\xe6\x02\n" +
	"\x14NotificationsService\x12o\n" +
	"\x12NotifyOrderCreated\x12*.notificationspb.NotifyOrderCreatedRequest\x1a+.notificationspb.NotifyOrderCreatedResponse\"\x00\x12r\n" +
	"\x13NotifyOrderCanceled\x12+.notificationspb.NotifyOrderCanceledRequest\x1a,.notificationspb.NotifyOrderCanceledResponse\"\x00\x12i\n" +
	"\x10NotifyOrderReady\x12(.notificationspb.NotifyOrderReadyRequest\x1a).notificationspb.NotifyOrderReadyResponse\"\x00B\xaf\x01\n" +
	"\x13com.notificationspbB\bApiProtoP\x01Z2mall/notifications/notificationspb/notificationspb\xa2\x02\x03NXX\xaa\x02\x0fNotificationspb\xca\x02\x0fNotificationspb\xe2\x02\x1bNotificationspb\\GPBMetadata\xea\x02\x0fNotificationspbb\x06proto3"

var (
	file_notificationspb_api_proto_rawDescOnce sync.Once
	file_notificationspb_api_proto_rawDescData []byte
)

func file_notificationspb_api_proto_rawDescGZIP() []byte {
	file_notificationspb_api_proto_rawDescOnce.Do(func() {
		file_notificationspb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notificationspb_api_proto_rawDesc), len(file_notificationspb_api_proto_rawDesc)))
	})
	return file_notificationspb_api_proto_rawDescData
}

var file_notificationspb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notificationspb_api_proto_goTypes = []any{
	(*NotifyOrderCreatedRequest)(nil),   // 0: notificationspb.NotifyOrderCreatedRequest
	(*NotifyOrderCreatedResponse)(nil),  // 1: notificationspb.NotifyOrderCreatedResponse
	(*NotifyOrderCanceledRequest)(nil),  // 2: notificationspb.NotifyOrderCanceledRequest
	(*NotifyOrderCanceledResponse)(nil), // 3: notificationspb.NotifyOrderCanceledResponse
	(*NotifyOrderReadyRequest)(nil),     // 4: notificationspb.NotifyOrderReadyRequest
	(*NotifyOrderReadyResponse)(nil),    // 5: notificationspb.NotifyOrderReadyResponse
}
var file_notificationspb_api_proto_depIdxs = []int32{
	0, // 0: notificationspb.NotificationsService.NotifyOrderCreated:input_type -> notificationspb.NotifyOrderCreatedRequest
	2, // 1: notificationspb.NotificationsService.NotifyOrderCanceled:input_type -> notificationspb.NotifyOrderCanceledRequest
	4, // 2: notificationspb.NotificationsService.NotifyOrderReady:input_type -> notificationspb.NotifyOrderReadyRequest
	1, // 3: notificationspb.NotificationsService.NotifyOrderCreated:output_type -> notificationspb.NotifyOrderCreatedResponse
	3, // 4: notificationspb.NotificationsService.NotifyOrderCanceled:output_type -> notificationspb.NotifyOrderCanceledResponse
	5, // 5: notificationspb.NotificationsService.NotifyOrderReady:output_type -> notificationspb.NotifyOrderReadyResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notificationspb_api_proto_init() }
func file_notificationspb_api_proto_init() {
	if File_notificationspb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notificationspb_api_proto_rawDesc), len(file_notificationspb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notificationspb_api_proto_goTypes,
		DependencyIndexes: file_notificationspb_api_proto_depIdxs,
		MessageInfos:      file_notificationspb_api_proto_msgTypes,
	}.Build()
	File_notificationspb_api_proto = out.File
	file_notificationspb_api_proto_goTypes = nil
	file_notificationspb_api_proto_depIdxs = nil
}
