// Code generated by MockGen. DO NOT EDIT.
// Source: mall/notifications/notificationspb (interfaces: NotificationsServiceClient,NotificationsServiceServer)
//
// Generated by this command:
//
//	mockgen -destination=notificationspb/mock.go -package=notificationspb mall/notifications/notificationspb NotificationsServiceClient,NotificationsServiceServer
//

// Package notificationspb is a generated GoMock package.
package notificationspb

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockNotificationsServiceClient is a mock of NotificationsServiceClient interface.
type MockNotificationsServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsServiceClientMockRecorder
	isgomock struct{}
}

// MockNotificationsServiceClientMockRecorder is the mock recorder for MockNotificationsServiceClient.
type MockNotificationsServiceClientMockRecorder struct {
	mock *MockNotificationsServiceClient
}

// NewMockNotificationsServiceClient creates a new mock instance.
func NewMockNotificationsServiceClient(ctrl *gomock.Controller) *MockNotificationsServiceClient {
	mock := &MockNotificationsServiceClient{ctrl: ctrl}
	mock.recorder = &MockNotificationsServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationsServiceClient) EXPECT() *MockNotificationsServiceClientMockRecorder {
	return m.recorder
}

// NotifyOrderCanceled mocks base method.
func (m *MockNotificationsServiceClient) NotifyOrderCanceled(ctx context.Context, in *NotifyOrderCanceledRequest, opts ...grpc.CallOption) (*NotifyOrderCanceledResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NotifyOrderCanceled", varargs...)
	ret0, _ := ret[0].(*NotifyOrderCanceledResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyOrderCanceled indicates an expected call of NotifyOrderCanceled.
func (mr *MockNotificationsServiceClientMockRecorder) NotifyOrderCanceled(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderCanceled", reflect.TypeOf((*MockNotificationsServiceClient)(nil).NotifyOrderCanceled), varargs...)
}

// NotifyOrderCreated mocks base method.
func (m *MockNotificationsServiceClient) NotifyOrderCreated(ctx context.Context, in *NotifyOrderCreatedRequest, opts ...grpc.CallOption) (*NotifyOrderCreatedResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NotifyOrderCreated", varargs...)
	ret0, _ := ret[0].(*NotifyOrderCreatedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyOrderCreated indicates an expected call of NotifyOrderCreated.
func (mr *MockNotificationsServiceClientMockRecorder) NotifyOrderCreated(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderCreated", reflect.TypeOf((*MockNotificationsServiceClient)(nil).NotifyOrderCreated), varargs...)
}

// NotifyOrderReady mocks base method.
func (m *MockNotificationsServiceClient) NotifyOrderReady(ctx context.Context, in *NotifyOrderReadyRequest, opts ...grpc.CallOption) (*NotifyOrderReadyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NotifyOrderReady", varargs...)
	ret0, _ := ret[0].(*NotifyOrderReadyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyOrderReady indicates an expected call of NotifyOrderReady.
func (mr *MockNotificationsServiceClientMockRecorder) NotifyOrderReady(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderReady", reflect.TypeOf((*MockNotificationsServiceClient)(nil).NotifyOrderReady), varargs...)
}

// MockNotificationsServiceServer is a mock of NotificationsServiceServer interface.
type MockNotificationsServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsServiceServerMockRecorder
	isgomock struct{}
}

// MockNotificationsServiceServerMockRecorder is the mock recorder for MockNotificationsServiceServer.
type MockNotificationsServiceServerMockRecorder struct {
	mock *MockNotificationsServiceServer
}

// NewMockNotificationsServiceServer creates a new mock instance.
func NewMockNotificationsServiceServer(ctrl *gomock.Controller) *MockNotificationsServiceServer {
	mock := &MockNotificationsServiceServer{ctrl: ctrl}
	mock.recorder = &MockNotificationsServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationsServiceServer) EXPECT() *MockNotificationsServiceServerMockRecorder {
	return m.recorder
}

// NotifyOrderCanceled mocks base method.
func (m *MockNotificationsServiceServer) NotifyOrderCanceled(arg0 context.Context, arg1 *NotifyOrderCanceledRequest) (*NotifyOrderCanceledResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyOrderCanceled", arg0, arg1)
	ret0, _ := ret[0].(*NotifyOrderCanceledResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyOrderCanceled indicates an expected call of NotifyOrderCanceled.
func (mr *MockNotificationsServiceServerMockRecorder) NotifyOrderCanceled(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderCanceled", reflect.TypeOf((*MockNotificationsServiceServer)(nil).NotifyOrderCanceled), arg0, arg1)
}

// NotifyOrderCreated mocks base method.
func (m *MockNotificationsServiceServer) NotifyOrderCreated(arg0 context.Context, arg1 *NotifyOrderCreatedRequest) (*NotifyOrderCreatedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyOrderCreated", arg0, arg1)
	ret0, _ := ret[0].(*NotifyOrderCreatedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyOrderCreated indicates an expected call of NotifyOrderCreated.
func (mr *MockNotificationsServiceServerMockRecorder) NotifyOrderCreated(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderCreated", reflect.TypeOf((*MockNotificationsServiceServer)(nil).NotifyOrderCreated), arg0, arg1)
}

// NotifyOrderReady mocks base method.
func (m *MockNotificationsServiceServer) NotifyOrderReady(arg0 context.Context, arg1 *NotifyOrderReadyRequest) (*NotifyOrderReadyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyOrderReady", arg0, arg1)
	ret0, _ := ret[0].(*NotifyOrderReadyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyOrderReady indicates an expected call of NotifyOrderReady.
func (mr *MockNotificationsServiceServerMockRecorder) NotifyOrderReady(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderReady", reflect.TypeOf((*MockNotificationsServiceServer)(nil).NotifyOrderReady), arg0, arg1)
}

// mustEmbedUnimplementedNotificationsServiceServer mocks base method.
func (m *MockNotificationsServiceServer) mustEmbedUnimplementedNotificationsServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedNotificationsServiceServer")
}

// mustEmbedUnimplementedNotificationsServiceServer indicates an expected call of mustEmbedUnimplementedNotificationsServiceServer.
func (mr *MockNotificationsServiceServerMockRecorder) mustEmbedUnimplementedNotificationsServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedNotificationsServiceServer", reflect.TypeOf((*MockNotificationsServiceServer)(nil).mustEmbedUnimplementedNotificationsServiceServer))
}
