// Code generated by MockGen. DO NOT EDIT.
// Source: mall/baskets/internal/domain (interfaces: BasketRepository,ProductCacheRepository,ProductRepository,StoreCacheRepository,StoreRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/domain/mock.go -package=domain mall/baskets/internal/domain BasketRepository,ProductCacheRepository,ProductRepository,StoreCacheRepository,StoreRepository
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBasketRepository is a mock of BasketRepository interface.
type MockBasketRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBasketRepositoryMockRecorder
	isgomock struct{}
}

// MockBasketRepositoryMockRecorder is the mock recorder for MockBasketRepository.
type MockBasketRepositoryMockRecorder struct {
	mock *MockBasketRepository
}

// NewMockBasketRepository creates a new mock instance.
func NewMockBasketRepository(ctrl *gomock.Controller) *MockBasketRepository {
	mock := &MockBasketRepository{ctrl: ctrl}
	mock.recorder = &MockBasketRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasketRepository) EXPECT() *MockBasketRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockBasketRepository) Load(ctx context.Context, basketID string) (*Basket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, basketID)
	ret0, _ := ret[0].(*Basket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockBasketRepositoryMockRecorder) Load(ctx, basketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockBasketRepository)(nil).Load), ctx, basketID)
}

// Save mocks base method.
func (m *MockBasketRepository) Save(ctx context.Context, basket *Basket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, basket)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockBasketRepositoryMockRecorder) Save(ctx, basket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBasketRepository)(nil).Save), ctx, basket)
}

// MockProductCacheRepository is a mock of ProductCacheRepository interface.
type MockProductCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockProductCacheRepositoryMockRecorder is the mock recorder for MockProductCacheRepository.
type MockProductCacheRepositoryMockRecorder struct {
	mock *MockProductCacheRepository
}

// NewMockProductCacheRepository creates a new mock instance.
func NewMockProductCacheRepository(ctrl *gomock.Controller) *MockProductCacheRepository {
	mock := &MockProductCacheRepository{ctrl: ctrl}
	mock.recorder = &MockProductCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductCacheRepository) EXPECT() *MockProductCacheRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockProductCacheRepository) Add(ctx context.Context, productID, storeID, name string, price float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, productID, storeID, name, price)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockProductCacheRepositoryMockRecorder) Add(ctx, productID, storeID, name, price any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockProductCacheRepository)(nil).Add), ctx, productID, storeID, name, price)
}

// Find mocks base method.
func (m *MockProductCacheRepository) Find(ctx context.Context, productID string) (*Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, productID)
	ret0, _ := ret[0].(*Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockProductCacheRepositoryMockRecorder) Find(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProductCacheRepository)(nil).Find), ctx, productID)
}

// Rebrand mocks base method.
func (m *MockProductCacheRepository) Rebrand(ctx context.Context, productID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rebrand", ctx, productID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rebrand indicates an expected call of Rebrand.
func (mr *MockProductCacheRepositoryMockRecorder) Rebrand(ctx, productID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rebrand", reflect.TypeOf((*MockProductCacheRepository)(nil).Rebrand), ctx, productID, name)
}

// Remove mocks base method.
func (m *MockProductCacheRepository) Remove(ctx context.Context, productID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockProductCacheRepositoryMockRecorder) Remove(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockProductCacheRepository)(nil).Remove), ctx, productID)
}

// UpdatePrice mocks base method.
func (m *MockProductCacheRepository) UpdatePrice(ctx context.Context, productID string, delta float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrice", ctx, productID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePrice indicates an expected call of UpdatePrice.
func (mr *MockProductCacheRepositoryMockRecorder) UpdatePrice(ctx, productID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePrice", reflect.TypeOf((*MockProductCacheRepository)(nil).UpdatePrice), ctx, productID, delta)
}

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockProductRepository) Find(ctx context.Context, productID string) (*Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, productID)
	ret0, _ := ret[0].(*Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockProductRepositoryMockRecorder) Find(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProductRepository)(nil).Find), ctx, productID)
}

// MockStoreCacheRepository is a mock of StoreCacheRepository interface.
type MockStoreCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoreCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockStoreCacheRepositoryMockRecorder is the mock recorder for MockStoreCacheRepository.
type MockStoreCacheRepositoryMockRecorder struct {
	mock *MockStoreCacheRepository
}

// NewMockStoreCacheRepository creates a new mock instance.
func NewMockStoreCacheRepository(ctrl *gomock.Controller) *MockStoreCacheRepository {
	mock := &MockStoreCacheRepository{ctrl: ctrl}
	mock.recorder = &MockStoreCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreCacheRepository) EXPECT() *MockStoreCacheRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockStoreCacheRepository) Add(ctx context.Context, storeID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, storeID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockStoreCacheRepositoryMockRecorder) Add(ctx, storeID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockStoreCacheRepository)(nil).Add), ctx, storeID, name)
}

// Find mocks base method.
func (m *MockStoreCacheRepository) Find(ctx context.Context, storeID string) (*Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, storeID)
	ret0, _ := ret[0].(*Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockStoreCacheRepositoryMockRecorder) Find(ctx, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStoreCacheRepository)(nil).Find), ctx, storeID)
}

// Rename mocks base method.
func (m *MockStoreCacheRepository) Rename(ctx context.Context, storeID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", ctx, storeID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockStoreCacheRepositoryMockRecorder) Rename(ctx, storeID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockStoreCacheRepository)(nil).Rename), ctx, storeID, name)
}

// MockStoreRepository is a mock of StoreRepository interface.
type MockStoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoreRepositoryMockRecorder
	isgomock struct{}
}

// MockStoreRepositoryMockRecorder is the mock recorder for MockStoreRepository.
type MockStoreRepositoryMockRecorder struct {
	mock *MockStoreRepository
}

// NewMockStoreRepository creates a new mock instance.
func NewMockStoreRepository(ctrl *gomock.Controller) *MockStoreRepository {
	mock := &MockStoreRepository{ctrl: ctrl}
	mock.recorder = &MockStoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreRepository) EXPECT() *MockStoreRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockStoreRepository) Find(ctx context.Context, storeID string) (*Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, storeID)
	ret0, _ := ret[0].(*Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockStoreRepositoryMockRecorder) Find(ctx, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStoreRepository)(nil).Find), ctx, storeID)
}
