// Code generated by MockGen. DO NOT EDIT.
// Source: mall/depot/internal/application (interfaces: App)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mock.go -package=application mall/depot/internal/application App
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	commands "mall/depot/internal/application/commands"
	queries "mall/depot/internal/application/queries"
	domain "mall/depot/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// AssignShoppingList mocks base method.
func (m *MockApp) AssignShoppingList(ctx context.Context, cmd commands.AssignShoppingListRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignShoppingList", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignShoppingList indicates an expected call of AssignShoppingList.
func (mr *MockAppMockRecorder) AssignShoppingList(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignShoppingList", reflect.TypeOf((*MockApp)(nil).AssignShoppingList), ctx, cmd)
}

// CancelShoppingList mocks base method.
func (m *MockApp) CancelShoppingList(ctx context.Context, cmd commands.CancelShoppingListRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelShoppingList", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelShoppingList indicates an expected call of CancelShoppingList.
func (mr *MockAppMockRecorder) CancelShoppingList(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelShoppingList", reflect.TypeOf((*MockApp)(nil).CancelShoppingList), ctx, cmd)
}

// CompleteShoppingList mocks base method.
func (m *MockApp) CompleteShoppingList(ctx context.Context, cmd commands.CompleteShoppingListRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteShoppingList", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteShoppingList indicates an expected call of CompleteShoppingList.
func (mr *MockAppMockRecorder) CompleteShoppingList(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteShoppingList", reflect.TypeOf((*MockApp)(nil).CompleteShoppingList), ctx, cmd)
}

// CreateShoppingList mocks base method.
func (m *MockApp) CreateShoppingList(ctx context.Context, cmd commands.CreateShoppingListRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShoppingList", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateShoppingList indicates an expected call of CreateShoppingList.
func (mr *MockAppMockRecorder) CreateShoppingList(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShoppingList", reflect.TypeOf((*MockApp)(nil).CreateShoppingList), ctx, cmd)
}

// GetShoppingList mocks base method.
func (m *MockApp) GetShoppingList(ctx context.Context, query queries.GetShoppingListRequest) (*domain.ShoppingList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShoppingList", ctx, query)
	ret0, _ := ret[0].(*domain.ShoppingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShoppingList indicates an expected call of GetShoppingList.
func (mr *MockAppMockRecorder) GetShoppingList(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShoppingList", reflect.TypeOf((*MockApp)(nil).GetShoppingList), ctx, query)
}

// InitiateShoppingList mocks base method.
func (m *MockApp) InitiateShoppingList(ctx context.Context, cmd commands.InitiateShoppingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateShoppingList", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitiateShoppingList indicates an expected call of InitiateShoppingList.
func (mr *MockAppMockRecorder) InitiateShoppingList(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateShoppingList", reflect.TypeOf((*MockApp)(nil).InitiateShoppingList), ctx, cmd)
}
