// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orderingpb/events.proto

package orderingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	ShoppingId    string                 `protobuf:"bytes,4,opt,name=shopping_id,json=shoppingId,proto3" json:"shopping_id,omitempty"`
	Items         []*OrderCreated_Item   `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreated) Reset() {
	*x = OrderCreated{}
	mi := &file_orderingpb_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated) ProtoMessage() {}

func (x *OrderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_orderingpb_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated.ProtoReflect.Descriptor instead.
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return file_orderingpb_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderCreated) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderCreated) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *OrderCreated) GetShoppingId() string {
	if x != nil {
		return x.ShoppingId
	}
	return ""
}

func (x *OrderCreated) GetItems() []*OrderCreated_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderReadied struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Total         float64                `protobuf:"fixed64,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderReadied) Reset() {
	*x = OrderReadied{}
	mi := &file_orderingpb_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderReadied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReadied) ProtoMessage() {}

func (x *OrderReadied) ProtoReflect() protoreflect.Message {
	mi := &file_orderingpb_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReadied.ProtoReflect.Descriptor instead.
func (*OrderReadied) Descriptor() ([]byte, []int) {
	return file_orderingpb_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderReadied) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderReadied) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderReadied) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *OrderReadied) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type OrderCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	InvoiceId     string                 `protobuf:"bytes,3,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCompleted) Reset() {
	*x = OrderCompleted{}
	mi := &file_orderingpb_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCompleted) ProtoMessage() {}

func (x *OrderCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_orderingpb_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCompleted.ProtoReflect.Descriptor instead.
func (*OrderCompleted) Descriptor() ([]byte, []int) {
	return file_orderingpb_events_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCompleted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderCompleted) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderCompleted) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type OrderCanceled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCanceled) Reset() {
	*x = OrderCanceled{}
	mi := &file_orderingpb_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCanceled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCanceled) ProtoMessage() {}

func (x *OrderCanceled) ProtoReflect() protoreflect.Message {
	mi := &file_orderingpb_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCanceled.ProtoReflect.Descriptor instead.
func (*OrderCanceled) Descriptor() ([]byte, []int) {
	return file_orderingpb_events_proto_rawDescGZIP(), []int{3}
}

func (x *OrderCanceled) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderCanceled) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderCanceled) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type OrderCreated_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreated_Item) Reset() {
	*x = OrderCreated_Item{}
	mi := &file_orderingpb_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreated_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated_Item) ProtoMessage() {}

func (x *OrderCreated_Item) ProtoReflect() protoreflect.Message {
	mi := &file_orderingpb_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated_Item.ProtoReflect.Descriptor instead.
func (*OrderCreated_Item) Descriptor() ([]byte, []int) {
	return file_orderingpb_events_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OrderCreated_Item) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderCreated_Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderCreated_Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_orderingpb_events_proto protoreflect.FileDescriptor

const file_orderingpb_events_proto_rawDesc = "" +
	"\n" +
	"\x17orderingpb/events.proto\x12\n" +
	"orderingpb\"\x8d\x02\n" +
	"\fOrderCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vshopping_id\x18\x04 \x01(\tR\n" +
	"shoppingId\x123\n" +
	"\x05items\x18\x05 \x03(\v2\x1d.orderingpb.OrderCreated.ItemR\x05items\x1aW\n" +
	"\x04Item\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"t\n" +
	"\fOrderReadied\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\tR\tpaymentId\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x01R\x05total\"`\n" +
	"\x0eOrderCompleted\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x03 \x01(\tR\tinvoiceId\"_\n" +
	"\rOrderCanceled\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\tR\tpaymentIdB\x8a\x01\n" +
	"\x0ecom.orderingpbB\vEventsProtoP\x01Z#mall/ordering/orderingpb/orderingpb\xa2\x02\x03OXX\xaa\x02\n" +
	"Orderingpb\xca\x02\n" +
	"Orderingpb\xe2\x02\x16Orderingpb\\GPBMetadata\xea\x02\n" +
	"Orderingpbb\x06proto3"

var (
	file_orderingpb_events_proto_rawDescOnce sync.Once
	file_orderingpb_events_proto_rawDescData []byte
)

func file_orderingpb_events_proto_rawDescGZIP() []byte {
	file_orderingpb_events_proto_rawDescOnce.Do(func() {
		file_orderingpb_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderingpb_events_proto_rawDesc), len(file_orderingpb_events_proto_rawDesc)))
	})
	return file_orderingpb_events_proto_rawDescData
}

var file_orderingpb_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_orderingpb_events_proto_goTypes = []any{
	(*OrderCreated)(nil),      // 0: orderingpb.OrderCreated
	(*OrderReadied)(nil),      // 1: orderingpb.OrderReadied
	(*OrderCompleted)(nil),    // 2: orderingpb.OrderCompleted
	(*OrderCanceled)(nil),     // 3: orderingpb.OrderCanceled
	(*OrderCreated_Item)(nil), // 4: orderingpb.OrderCreated.Item
}
var file_orderingpb_events_proto_depIdxs = []int32{
	4, // 0: orderingpb.OrderCreated.items:type_name -> orderingpb.OrderCreated.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orderingpb_events_proto_init() }
func file_orderingpb_events_proto_init() {
	if File_orderingpb_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderingpb_events_proto_rawDesc), len(file_orderingpb_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orderingpb_events_proto_goTypes,
		DependencyIndexes: file_orderingpb_events_proto_depIdxs,
		MessageInfos:      file_orderingpb_events_proto_msgTypes,
	}.Build()
	File_orderingpb_events_proto = out.File
	file_orderingpb_events_proto_goTypes = nil
	file_orderingpb_events_proto_depIdxs = nil
}
