// Code generated by MockGen. DO NOT EDIT.
// Source: mall/ordering/orderingpb (interfaces: OrderingServiceClient,OrderingServiceServer)
//
// Generated by this command:
//
//	mockgen -destination=orderingpb/mock.go -package=orderingpb mall/ordering/orderingpb OrderingServiceClient,OrderingServiceServer
//

// Package orderingpb is a generated GoMock package.
package orderingpb

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockOrderingServiceClient is a mock of OrderingServiceClient interface.
type MockOrderingServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrderingServiceClientMockRecorder
	isgomock struct{}
}

// MockOrderingServiceClientMockRecorder is the mock recorder for MockOrderingServiceClient.
type MockOrderingServiceClientMockRecorder struct {
	mock *MockOrderingServiceClient
}

// NewMockOrderingServiceClient creates a new mock instance.
func NewMockOrderingServiceClient(ctrl *gomock.Controller) *MockOrderingServiceClient {
	mock := &MockOrderingServiceClient{ctrl: ctrl}
	mock.recorder = &MockOrderingServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderingServiceClient) EXPECT() *MockOrderingServiceClientMockRecorder {
	return m.recorder
}

// CancelOrder mocks base method.
func (m *MockOrderingServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelOrder", varargs...)
	ret0, _ := ret[0].(*CancelOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockOrderingServiceClientMockRecorder) CancelOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockOrderingServiceClient)(nil).CancelOrder), varargs...)
}

// CompleteOrder mocks base method.
func (m *MockOrderingServiceClient) CompleteOrder(ctx context.Context, in *CompleteOrderRequest, opts ...grpc.CallOption) (*CompleteOrderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CompleteOrder", varargs...)
	ret0, _ := ret[0].(*CompleteOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteOrder indicates an expected call of CompleteOrder.
func (mr *MockOrderingServiceClientMockRecorder) CompleteOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteOrder", reflect.TypeOf((*MockOrderingServiceClient)(nil).CompleteOrder), varargs...)
}

// CreateOrder mocks base method.
func (m *MockOrderingServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateOrder", varargs...)
	ret0, _ := ret[0].(*CreateOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderingServiceClientMockRecorder) CreateOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderingServiceClient)(nil).CreateOrder), varargs...)
}

// GetOrder mocks base method.
func (m *MockOrderingServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrder", varargs...)
	ret0, _ := ret[0].(*GetOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderingServiceClientMockRecorder) GetOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderingServiceClient)(nil).GetOrder), varargs...)
}

// ReadyOrder mocks base method.
func (m *MockOrderingServiceClient) ReadyOrder(ctx context.Context, in *ReadyOrderRequest, opts ...grpc.CallOption) (*ReadyOrderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReadyOrder", varargs...)
	ret0, _ := ret[0].(*ReadyOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadyOrder indicates an expected call of ReadyOrder.
func (mr *MockOrderingServiceClientMockRecorder) ReadyOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadyOrder", reflect.TypeOf((*MockOrderingServiceClient)(nil).ReadyOrder), varargs...)
}

// MockOrderingServiceServer is a mock of OrderingServiceServer interface.
type MockOrderingServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockOrderingServiceServerMockRecorder
	isgomock struct{}
}

// MockOrderingServiceServerMockRecorder is the mock recorder for MockOrderingServiceServer.
type MockOrderingServiceServerMockRecorder struct {
	mock *MockOrderingServiceServer
}

// NewMockOrderingServiceServer creates a new mock instance.
func NewMockOrderingServiceServer(ctrl *gomock.Controller) *MockOrderingServiceServer {
	mock := &MockOrderingServiceServer{ctrl: ctrl}
	mock.recorder = &MockOrderingServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderingServiceServer) EXPECT() *MockOrderingServiceServerMockRecorder {
	return m.recorder
}

// CancelOrder mocks base method.
func (m *MockOrderingServiceServer) CancelOrder(arg0 context.Context, arg1 *CancelOrderRequest) (*CancelOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", arg0, arg1)
	ret0, _ := ret[0].(*CancelOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockOrderingServiceServerMockRecorder) CancelOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockOrderingServiceServer)(nil).CancelOrder), arg0, arg1)
}

// CompleteOrder mocks base method.
func (m *MockOrderingServiceServer) CompleteOrder(arg0 context.Context, arg1 *CompleteOrderRequest) (*CompleteOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteOrder", arg0, arg1)
	ret0, _ := ret[0].(*CompleteOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteOrder indicates an expected call of CompleteOrder.
func (mr *MockOrderingServiceServerMockRecorder) CompleteOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteOrder", reflect.TypeOf((*MockOrderingServiceServer)(nil).CompleteOrder), arg0, arg1)
}

// CreateOrder mocks base method.
func (m *MockOrderingServiceServer) CreateOrder(arg0 context.Context, arg1 *CreateOrderRequest) (*CreateOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1)
	ret0, _ := ret[0].(*CreateOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderingServiceServerMockRecorder) CreateOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderingServiceServer)(nil).CreateOrder), arg0, arg1)
}

// GetOrder mocks base method.
func (m *MockOrderingServiceServer) GetOrder(arg0 context.Context, arg1 *GetOrderRequest) (*GetOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", arg0, arg1)
	ret0, _ := ret[0].(*GetOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderingServiceServerMockRecorder) GetOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderingServiceServer)(nil).GetOrder), arg0, arg1)
}

// ReadyOrder mocks base method.
func (m *MockOrderingServiceServer) ReadyOrder(arg0 context.Context, arg1 *ReadyOrderRequest) (*ReadyOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadyOrder", arg0, arg1)
	ret0, _ := ret[0].(*ReadyOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadyOrder indicates an expected call of ReadyOrder.
func (mr *MockOrderingServiceServerMockRecorder) ReadyOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadyOrder", reflect.TypeOf((*MockOrderingServiceServer)(nil).ReadyOrder), arg0, arg1)
}

// mustEmbedUnimplementedOrderingServiceServer mocks base method.
func (m *MockOrderingServiceServer) mustEmbedUnimplementedOrderingServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedOrderingServiceServer")
}

// mustEmbedUnimplementedOrderingServiceServer indicates an expected call of mustEmbedUnimplementedOrderingServiceServer.
func (mr *MockOrderingServiceServerMockRecorder) mustEmbedUnimplementedOrderingServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedOrderingServiceServer", reflect.TypeOf((*MockOrderingServiceServer)(nil).mustEmbedUnimplementedOrderingServiceServer))
}
