// Code generated by MockGen. DO NOT EDIT.
// Source: mall/stores/internal/application (interfaces: App)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mock.go -package=application mall/stores/internal/application App
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	commands "mall/stores/internal/application/commands"
	queries "mall/stores/internal/application/queries"
	domain "mall/stores/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// AddProduct mocks base method.
func (m *MockApp) AddProduct(ctx context.Context, cmd commands.AddProductRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockAppMockRecorder) AddProduct(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockApp)(nil).AddProduct), ctx, cmd)
}

// CreateStore mocks base method.
func (m *MockApp) CreateStore(ctx context.Context, cmd commands.CreateStoreRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStore", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockAppMockRecorder) CreateStore(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockApp)(nil).CreateStore), ctx, cmd)
}

// DecreaseProductPrice mocks base method.
func (m *MockApp) DecreaseProductPrice(ctx context.Context, cmd commands.DecreaseProductPriceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseProductPrice", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecreaseProductPrice indicates an expected call of DecreaseProductPrice.
func (mr *MockAppMockRecorder) DecreaseProductPrice(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseProductPrice", reflect.TypeOf((*MockApp)(nil).DecreaseProductPrice), ctx, cmd)
}

// DisableParticipation mocks base method.
func (m *MockApp) DisableParticipation(ctx context.Context, cmd commands.DisableParticipationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableParticipation", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableParticipation indicates an expected call of DisableParticipation.
func (mr *MockAppMockRecorder) DisableParticipation(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableParticipation", reflect.TypeOf((*MockApp)(nil).DisableParticipation), ctx, cmd)
}

// EnableParticipation mocks base method.
func (m *MockApp) EnableParticipation(ctx context.Context, cmd commands.EnableParticipationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableParticipation", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableParticipation indicates an expected call of EnableParticipation.
func (mr *MockAppMockRecorder) EnableParticipation(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableParticipation", reflect.TypeOf((*MockApp)(nil).EnableParticipation), ctx, cmd)
}

// GetCatalog mocks base method.
func (m *MockApp) GetCatalog(ctx context.Context, query queries.GetCatalogRequest) ([]*domain.CatalogProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCatalog", ctx, query)
	ret0, _ := ret[0].([]*domain.CatalogProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCatalog indicates an expected call of GetCatalog.
func (mr *MockAppMockRecorder) GetCatalog(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCatalog", reflect.TypeOf((*MockApp)(nil).GetCatalog), ctx, query)
}

// GetParticipatingStores mocks base method.
func (m *MockApp) GetParticipatingStores(ctx context.Context, query queries.GetParticipatingStoreRequest) ([]*domain.MallStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipatingStores", ctx, query)
	ret0, _ := ret[0].([]*domain.MallStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipatingStores indicates an expected call of GetParticipatingStores.
func (mr *MockAppMockRecorder) GetParticipatingStores(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipatingStores", reflect.TypeOf((*MockApp)(nil).GetParticipatingStores), ctx, query)
}

// GetProduct mocks base method.
func (m *MockApp) GetProduct(ctx context.Context, query queries.GetProductRequest) (*domain.CatalogProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, query)
	ret0, _ := ret[0].(*domain.CatalogProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockAppMockRecorder) GetProduct(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockApp)(nil).GetProduct), ctx, query)
}

// GetStore mocks base method.
func (m *MockApp) GetStore(ctx context.Context, query queries.GetStoreRequest) (*domain.MallStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore", ctx, query)
	ret0, _ := ret[0].(*domain.MallStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStore indicates an expected call of GetStore.
func (mr *MockAppMockRecorder) GetStore(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockApp)(nil).GetStore), ctx, query)
}

// GetStores mocks base method.
func (m *MockApp) GetStores(ctx context.Context, query queries.GetStoresRequest) ([]*domain.MallStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStores", ctx, query)
	ret0, _ := ret[0].([]*domain.MallStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStores indicates an expected call of GetStores.
func (mr *MockAppMockRecorder) GetStores(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStores", reflect.TypeOf((*MockApp)(nil).GetStores), ctx, query)
}

// IncreaseProductPrice mocks base method.
func (m *MockApp) IncreaseProductPrice(ctx context.Context, cmd commands.IncreaseProductPriceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseProductPrice", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseProductPrice indicates an expected call of IncreaseProductPrice.
func (mr *MockAppMockRecorder) IncreaseProductPrice(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseProductPrice", reflect.TypeOf((*MockApp)(nil).IncreaseProductPrice), ctx, cmd)
}

// RebrandProduct mocks base method.
func (m *MockApp) RebrandProduct(ctx context.Context, cmd commands.RebrandProductRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebrandProduct", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebrandProduct indicates an expected call of RebrandProduct.
func (mr *MockAppMockRecorder) RebrandProduct(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebrandProduct", reflect.TypeOf((*MockApp)(nil).RebrandProduct), ctx, cmd)
}

// RebrandStore mocks base method.
func (m *MockApp) RebrandStore(ctx context.Context, cmd commands.RebrandStoreRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebrandStore", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebrandStore indicates an expected call of RebrandStore.
func (mr *MockAppMockRecorder) RebrandStore(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebrandStore", reflect.TypeOf((*MockApp)(nil).RebrandStore), ctx, cmd)
}

// RemoveProduct mocks base method.
func (m *MockApp) RemoveProduct(ctx context.Context, cmd commands.RemoveProductRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveProduct", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveProduct indicates an expected call of RemoveProduct.
func (mr *MockAppMockRecorder) RemoveProduct(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveProduct", reflect.TypeOf((*MockApp)(nil).RemoveProduct), ctx, cmd)
}
