apiVersion: v1
kind: Service
metadata:
    name: notifications-service
spec:
    selector:
      app: notifications
    ports:
    - name: rest
      protocol: TCP
      port: 8080 # cluster assigned ip port
      targetPort: 8080 # pod container ip port
    - name: grpc
      protocol: TCP
      port: 9000 # cluster assigned ip port
      targetPort: 9000 # pod container ip port