// Code generated by MockGen. DO NOT EDIT.
// Source: mall/notifications/internal/domain (interfaces: CustomerCacheRepository,CustomerRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/domain/mock.go -package=domain mall/notifications/internal/domain CustomerCacheRepository,CustomerRepository
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCustomerCacheRepository is a mock of CustomerCacheRepository interface.
type MockCustomerCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerCacheRepositoryMockRecorder is the mock recorder for MockCustomerCacheRepository.
type MockCustomerCacheRepositoryMockRecorder struct {
	mock *MockCustomerCacheRepository
}

// NewMockCustomerCacheRepository creates a new mock instance.
func NewMockCustomerCacheRepository(ctrl *gomock.Controller) *MockCustomerCacheRepository {
	mock := &MockCustomerCacheRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerCacheRepository) EXPECT() *MockCustomerCacheRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCustomerCacheRepository) Add(ctx context.Context, customerID, name, smsNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, customerID, name, smsNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockCustomerCacheRepositoryMockRecorder) Add(ctx, customerID, name, smsNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCustomerCacheRepository)(nil).Add), ctx, customerID, name, smsNumber)
}

// Find mocks base method.
func (m *MockCustomerCacheRepository) Find(ctx context.Context, customerID string) (*Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, customerID)
	ret0, _ := ret[0].(*Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCustomerCacheRepositoryMockRecorder) Find(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCustomerCacheRepository)(nil).Find), ctx, customerID)
}

// UpdateSmsNumber mocks base method.
func (m *MockCustomerCacheRepository) UpdateSmsNumber(ctx context.Context, customerID, smsNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSmsNumber", ctx, customerID, smsNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSmsNumber indicates an expected call of UpdateSmsNumber.
func (mr *MockCustomerCacheRepositoryMockRecorder) UpdateSmsNumber(ctx, customerID, smsNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSmsNumber", reflect.TypeOf((*MockCustomerCacheRepository)(nil).UpdateSmsNumber), ctx, customerID, smsNumber)
}

// MockCustomerRepository is a mock of CustomerRepository interface.
type MockCustomerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerRepositoryMockRecorder is the mock recorder for MockCustomerRepository.
type MockCustomerRepositoryMockRecorder struct {
	mock *MockCustomerRepository
}

// NewMockCustomerRepository creates a new mock instance.
func NewMockCustomerRepository(ctrl *gomock.Controller) *MockCustomerRepository {
	mock := &MockCustomerRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerRepository) EXPECT() *MockCustomerRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockCustomerRepository) Find(ctx context.Context, customerID string) (*Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, customerID)
	ret0, _ := ret[0].(*Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCustomerRepositoryMockRecorder) Find(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCustomerRepository)(nil).Find), ctx, customerID)
}
