// Code generated by MockGen. DO NOT EDIT.
// Source: mall/payments/internal/domain (interfaces: InvoiceRepository,PaymentRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/domain/mock.go -package=domain mall/payments/internal/domain InvoiceRepository,PaymentRepository
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInvoiceRepository is a mock of InvoiceRepository interface.
type MockInvoiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceRepositoryMockRecorder
	isgomock struct{}
}

// MockInvoiceRepositoryMockRecorder is the mock recorder for MockInvoiceRepository.
type MockInvoiceRepositoryMockRecorder struct {
	mock *MockInvoiceRepository
}

// NewMockInvoiceRepository creates a new mock instance.
func NewMockInvoiceRepository(ctrl *gomock.Controller) *MockInvoiceRepository {
	mock := &MockInvoiceRepository{ctrl: ctrl}
	mock.recorder = &MockInvoiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceRepository) EXPECT() *MockInvoiceRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockInvoiceRepository) Find(ctx context.Context, invoiceID string) (*Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, invoiceID)
	ret0, _ := ret[0].(*Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockInvoiceRepositoryMockRecorder) Find(ctx, invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockInvoiceRepository)(nil).Find), ctx, invoiceID)
}

// Save mocks base method.
func (m *MockInvoiceRepository) Save(ctx context.Context, invoice *Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockInvoiceRepositoryMockRecorder) Save(ctx, invoice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockInvoiceRepository)(nil).Save), ctx, invoice)
}

// Update mocks base method.
func (m *MockInvoiceRepository) Update(ctx context.Context, invoice *Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInvoiceRepositoryMockRecorder) Update(ctx, invoice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvoiceRepository)(nil).Update), ctx, invoice)
}

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockPaymentRepository) Find(ctx context.Context, paymentID string) (*Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, paymentID)
	ret0, _ := ret[0].(*Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockPaymentRepositoryMockRecorder) Find(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPaymentRepository)(nil).Find), ctx, paymentID)
}

// Save mocks base method.
func (m *MockPaymentRepository) Save(ctx context.Context, payment *Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPaymentRepositoryMockRecorder) Save(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPaymentRepository)(nil).Save), ctx, payment)
}
