// Code generated by MockGen. DO NOT EDIT.
// Source: mall/depot/internal/domain (interfaces: OrderRepository,ProductCacheRepository,ProductRepository,ShoppingListRepository,StoreCacheRepository,StoreRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/domain/mock.go -package=domain mall/depot/internal/domain OrderRepository,ProductCacheRepository,ProductRepository,ShoppingListRepository,StoreCacheRepository,StoreRepository
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// Ready mocks base method.
func (m *MockOrderRepository) Ready(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ready", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ready indicates an expected call of Ready.
func (mr *MockOrderRepositoryMockRecorder) Ready(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ready", reflect.TypeOf((*MockOrderRepository)(nil).Ready), ctx, orderID)
}

// MockProductCacheRepository is a mock of ProductCacheRepository interface.
type MockProductCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockProductCacheRepositoryMockRecorder is the mock recorder for MockProductCacheRepository.
type MockProductCacheRepositoryMockRecorder struct {
	mock *MockProductCacheRepository
}

// NewMockProductCacheRepository creates a new mock instance.
func NewMockProductCacheRepository(ctrl *gomock.Controller) *MockProductCacheRepository {
	mock := &MockProductCacheRepository{ctrl: ctrl}
	mock.recorder = &MockProductCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductCacheRepository) EXPECT() *MockProductCacheRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockProductCacheRepository) Add(ctx context.Context, productID, storeID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, productID, storeID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockProductCacheRepositoryMockRecorder) Add(ctx, productID, storeID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockProductCacheRepository)(nil).Add), ctx, productID, storeID, name)
}

// Find mocks base method.
func (m *MockProductCacheRepository) Find(ctx context.Context, productID string) (*Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, productID)
	ret0, _ := ret[0].(*Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockProductCacheRepositoryMockRecorder) Find(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProductCacheRepository)(nil).Find), ctx, productID)
}

// Rebrand mocks base method.
func (m *MockProductCacheRepository) Rebrand(ctx context.Context, productID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rebrand", ctx, productID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rebrand indicates an expected call of Rebrand.
func (mr *MockProductCacheRepositoryMockRecorder) Rebrand(ctx, productID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rebrand", reflect.TypeOf((*MockProductCacheRepository)(nil).Rebrand), ctx, productID, name)
}

// Remove mocks base method.
func (m *MockProductCacheRepository) Remove(ctx context.Context, productID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockProductCacheRepositoryMockRecorder) Remove(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockProductCacheRepository)(nil).Remove), ctx, productID)
}

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockProductRepository) Find(ctx context.Context, productID string) (*Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, productID)
	ret0, _ := ret[0].(*Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockProductRepositoryMockRecorder) Find(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProductRepository)(nil).Find), ctx, productID)
}

// MockShoppingListRepository is a mock of ShoppingListRepository interface.
type MockShoppingListRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShoppingListRepositoryMockRecorder
	isgomock struct{}
}

// MockShoppingListRepositoryMockRecorder is the mock recorder for MockShoppingListRepository.
type MockShoppingListRepositoryMockRecorder struct {
	mock *MockShoppingListRepository
}

// NewMockShoppingListRepository creates a new mock instance.
func NewMockShoppingListRepository(ctrl *gomock.Controller) *MockShoppingListRepository {
	mock := &MockShoppingListRepository{ctrl: ctrl}
	mock.recorder = &MockShoppingListRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShoppingListRepository) EXPECT() *MockShoppingListRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockShoppingListRepository) Find(ctx context.Context, shoppingListID string) (*ShoppingList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, shoppingListID)
	ret0, _ := ret[0].(*ShoppingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockShoppingListRepositoryMockRecorder) Find(ctx, shoppingListID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockShoppingListRepository)(nil).Find), ctx, shoppingListID)
}

// Save mocks base method.
func (m *MockShoppingListRepository) Save(ctx context.Context, list *ShoppingList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, list)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockShoppingListRepositoryMockRecorder) Save(ctx, list any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockShoppingListRepository)(nil).Save), ctx, list)
}

// Update mocks base method.
func (m *MockShoppingListRepository) Update(ctx context.Context, list *ShoppingList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, list)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockShoppingListRepositoryMockRecorder) Update(ctx, list any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShoppingListRepository)(nil).Update), ctx, list)
}

// MockStoreCacheRepository is a mock of StoreCacheRepository interface.
type MockStoreCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoreCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockStoreCacheRepositoryMockRecorder is the mock recorder for MockStoreCacheRepository.
type MockStoreCacheRepositoryMockRecorder struct {
	mock *MockStoreCacheRepository
}

// NewMockStoreCacheRepository creates a new mock instance.
func NewMockStoreCacheRepository(ctrl *gomock.Controller) *MockStoreCacheRepository {
	mock := &MockStoreCacheRepository{ctrl: ctrl}
	mock.recorder = &MockStoreCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreCacheRepository) EXPECT() *MockStoreCacheRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockStoreCacheRepository) Add(ctx context.Context, storeID, name, location string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, storeID, name, location)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockStoreCacheRepositoryMockRecorder) Add(ctx, storeID, name, location any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockStoreCacheRepository)(nil).Add), ctx, storeID, name, location)
}

// Find mocks base method.
func (m *MockStoreCacheRepository) Find(ctx context.Context, id string) (*Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockStoreCacheRepositoryMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStoreCacheRepository)(nil).Find), ctx, id)
}

// Rename mocks base method.
func (m *MockStoreCacheRepository) Rename(ctx context.Context, storeID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", ctx, storeID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockStoreCacheRepositoryMockRecorder) Rename(ctx, storeID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockStoreCacheRepository)(nil).Rename), ctx, storeID, name)
}

// MockStoreRepository is a mock of StoreRepository interface.
type MockStoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoreRepositoryMockRecorder
	isgomock struct{}
}

// MockStoreRepositoryMockRecorder is the mock recorder for MockStoreRepository.
type MockStoreRepositoryMockRecorder struct {
	mock *MockStoreRepository
}

// NewMockStoreRepository creates a new mock instance.
func NewMockStoreRepository(ctrl *gomock.Controller) *MockStoreRepository {
	mock := &MockStoreRepository{ctrl: ctrl}
	mock.recorder = &MockStoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreRepository) EXPECT() *MockStoreRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockStoreRepository) Find(ctx context.Context, id string) (*Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockStoreRepositoryMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStoreRepository)(nil).Find), ctx, id)
}
