// Code generated by MockGen. DO NOT EDIT.
// Source: mall/internal/es (interfaces: AggregateRepository,AggregateStore,EventSourcedAggregate,Aggregate)
//
// Generated by this command:
//
//	mockgen -destination=mock.go -package=es mall/internal/es AggregateRepository,AggregateStore,EventSourcedAggregate,Aggregate
//

// Package es is a generated GoMock package.
package es

import (
	context "context"
	ddd "mall/internal/ddd"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAggregateRepository is a mock of AggregateRepository interface.
type MockAggregateRepository[T EventSourcedAggregate] struct {
	ctrl     *gomock.Controller
	recorder *MockAggregateRepositoryMockRecorder[T]
	isgomock struct{}
}

// MockAggregateRepositoryMockRecorder is the mock recorder for MockAggregateRepository.
type MockAggregateRepositoryMockRecorder[T EventSourcedAggregate] struct {
	mock *MockAggregateRepository[T]
}

// NewMockAggregateRepository creates a new mock instance.
func NewMockAggregateRepository[T EventSourcedAggregate](ctrl *gomock.Controller) *MockAggregateRepository[T] {
	mock := &MockAggregateRepository[T]{ctrl: ctrl}
	mock.recorder = &MockAggregateRepositoryMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregateRepository[T]) EXPECT() *MockAggregateRepositoryMockRecorder[T] {
	return m.recorder
}

// Load mocks base method.
func (m *MockAggregateRepository[T]) Load(ctx context.Context, aggregateID string) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, aggregateID)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockAggregateRepositoryMockRecorder[T]) Load(ctx, aggregateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockAggregateRepository[T])(nil).Load), ctx, aggregateID)
}

// Save mocks base method.
func (m *MockAggregateRepository[T]) Save(ctx context.Context, aggregate T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, aggregate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAggregateRepositoryMockRecorder[T]) Save(ctx, aggregate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAggregateRepository[T])(nil).Save), ctx, aggregate)
}

// MockAggregateStore is a mock of AggregateStore interface.
type MockAggregateStore struct {
	ctrl     *gomock.Controller
	recorder *MockAggregateStoreMockRecorder
	isgomock struct{}
}

// MockAggregateStoreMockRecorder is the mock recorder for MockAggregateStore.
type MockAggregateStoreMockRecorder struct {
	mock *MockAggregateStore
}

// NewMockAggregateStore creates a new mock instance.
func NewMockAggregateStore(ctrl *gomock.Controller) *MockAggregateStore {
	mock := &MockAggregateStore{ctrl: ctrl}
	mock.recorder = &MockAggregateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregateStore) EXPECT() *MockAggregateStoreMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockAggregateStore) Load(ctx context.Context, aggregate EventSourcedAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, aggregate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockAggregateStoreMockRecorder) Load(ctx, aggregate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockAggregateStore)(nil).Load), ctx, aggregate)
}

// Save mocks base method.
func (m *MockAggregateStore) Save(ctx context.Context, aggregate EventSourcedAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, aggregate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAggregateStoreMockRecorder) Save(ctx, aggregate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAggregateStore)(nil).Save), ctx, aggregate)
}

// MockEventSourcedAggregate is a mock of EventSourcedAggregate interface.
type MockEventSourcedAggregate struct {
	ctrl     *gomock.Controller
	recorder *MockEventSourcedAggregateMockRecorder
	isgomock struct{}
}

// MockEventSourcedAggregateMockRecorder is the mock recorder for MockEventSourcedAggregate.
type MockEventSourcedAggregateMockRecorder struct {
	mock *MockEventSourcedAggregate
}

// NewMockEventSourcedAggregate creates a new mock instance.
func NewMockEventSourcedAggregate(ctrl *gomock.Controller) *MockEventSourcedAggregate {
	mock := &MockEventSourcedAggregate{ctrl: ctrl}
	mock.recorder = &MockEventSourcedAggregateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventSourcedAggregate) EXPECT() *MockEventSourcedAggregateMockRecorder {
	return m.recorder
}

// AddEvent mocks base method.
func (m *MockEventSourcedAggregate) AddEvent(arg0 string, arg1 ddd.EventPayload, arg2 ...ddd.EventOption) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddEvent", varargs...)
}

// AddEvent indicates an expected call of AddEvent.
func (mr *MockEventSourcedAggregateMockRecorder) AddEvent(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEvent", reflect.TypeOf((*MockEventSourcedAggregate)(nil).AddEvent), varargs...)
}

// AggregateName mocks base method.
func (m *MockEventSourcedAggregate) AggregateName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateName")
	ret0, _ := ret[0].(string)
	return ret0
}

// AggregateName indicates an expected call of AggregateName.
func (mr *MockEventSourcedAggregateMockRecorder) AggregateName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateName", reflect.TypeOf((*MockEventSourcedAggregate)(nil).AggregateName))
}

// ApplyEvent mocks base method.
func (m *MockEventSourcedAggregate) ApplyEvent(arg0 ddd.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyEvent indicates an expected call of ApplyEvent.
func (mr *MockEventSourcedAggregateMockRecorder) ApplyEvent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyEvent", reflect.TypeOf((*MockEventSourcedAggregate)(nil).ApplyEvent), arg0)
}

// ClearEvents mocks base method.
func (m *MockEventSourcedAggregate) ClearEvents() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearEvents")
}

// ClearEvents indicates an expected call of ClearEvents.
func (mr *MockEventSourcedAggregateMockRecorder) ClearEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearEvents", reflect.TypeOf((*MockEventSourcedAggregate)(nil).ClearEvents))
}

// CommitEvents mocks base method.
func (m *MockEventSourcedAggregate) CommitEvents() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CommitEvents")
}

// CommitEvents indicates an expected call of CommitEvents.
func (mr *MockEventSourcedAggregateMockRecorder) CommitEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitEvents", reflect.TypeOf((*MockEventSourcedAggregate)(nil).CommitEvents))
}

// GetEvents mocks base method.
func (m *MockEventSourcedAggregate) GetEvents() []ddd.AggregateEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvents")
	ret0, _ := ret[0].([]ddd.AggregateEvent)
	return ret0
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockEventSourcedAggregateMockRecorder) GetEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockEventSourcedAggregate)(nil).GetEvents))
}

// ID mocks base method.
func (m *MockEventSourcedAggregate) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockEventSourcedAggregateMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockEventSourcedAggregate)(nil).ID))
}

// PendingVersion mocks base method.
func (m *MockEventSourcedAggregate) PendingVersion() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingVersion")
	ret0, _ := ret[0].(int)
	return ret0
}

// PendingVersion indicates an expected call of PendingVersion.
func (mr *MockEventSourcedAggregateMockRecorder) PendingVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingVersion", reflect.TypeOf((*MockEventSourcedAggregate)(nil).PendingVersion))
}

// Version mocks base method.
func (m *MockEventSourcedAggregate) Version() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(int)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockEventSourcedAggregateMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockEventSourcedAggregate)(nil).Version))
}

// MockAggregate is a mock of Aggregate interface.
type MockAggregate struct {
	ctrl     *gomock.Controller
	recorder *MockAggregateMockRecorder
	isgomock struct{}
}

// MockAggregateMockRecorder is the mock recorder for MockAggregate.
type MockAggregateMockRecorder struct {
	mock *MockAggregate
}

// NewMockAggregate creates a new mock instance.
func NewMockAggregate(ctrl *gomock.Controller) *MockAggregate {
	mock := &MockAggregate{ctrl: ctrl}
	mock.recorder = &MockAggregateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregate) EXPECT() *MockAggregateMockRecorder {
	return m.recorder
}

// AddEvent mocks base method.
func (m *MockAggregate) AddEvent(arg0 string, arg1 ddd.EventPayload, arg2 ...ddd.EventOption) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddEvent", varargs...)
}

// AddEvent indicates an expected call of AddEvent.
func (mr *MockAggregateMockRecorder) AddEvent(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEvent", reflect.TypeOf((*MockAggregate)(nil).AddEvent), varargs...)
}

// AggregateName mocks base method.
func (m *MockAggregate) AggregateName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateName")
	ret0, _ := ret[0].(string)
	return ret0
}

// AggregateName indicates an expected call of AggregateName.
func (mr *MockAggregateMockRecorder) AggregateName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateName", reflect.TypeOf((*MockAggregate)(nil).AggregateName))
}

// ClearEvents mocks base method.
func (m *MockAggregate) ClearEvents() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearEvents")
}

// ClearEvents indicates an expected call of ClearEvents.
func (mr *MockAggregateMockRecorder) ClearEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearEvents", reflect.TypeOf((*MockAggregate)(nil).ClearEvents))
}

// CommitEvents mocks base method.
func (m *MockAggregate) CommitEvents() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CommitEvents")
}

// CommitEvents indicates an expected call of CommitEvents.
func (mr *MockAggregateMockRecorder) CommitEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitEvents", reflect.TypeOf((*MockAggregate)(nil).CommitEvents))
}

// GetEvents mocks base method.
func (m *MockAggregate) GetEvents() []ddd.AggregateEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvents")
	ret0, _ := ret[0].([]ddd.AggregateEvent)
	return ret0
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockAggregateMockRecorder) GetEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockAggregate)(nil).GetEvents))
}

// ID mocks base method.
func (m *MockAggregate) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockAggregateMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockAggregate)(nil).ID))
}

// PendingVersion mocks base method.
func (m *MockAggregate) PendingVersion() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingVersion")
	ret0, _ := ret[0].(int)
	return ret0
}

// PendingVersion indicates an expected call of PendingVersion.
func (mr *MockAggregateMockRecorder) PendingVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingVersion", reflect.TypeOf((*MockAggregate)(nil).PendingVersion))
}

// SetID mocks base method.
func (m *MockAggregate) SetID(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetID", arg0)
}

// SetID indicates an expected call of SetID.
func (mr *MockAggregateMockRecorder) SetID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetID", reflect.TypeOf((*MockAggregate)(nil).SetID), arg0)
}

// SetName mocks base method.
func (m *MockAggregate) SetName(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetName", arg0)
}

// SetName indicates an expected call of SetName.
func (mr *MockAggregateMockRecorder) SetName(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetName", reflect.TypeOf((*MockAggregate)(nil).SetName), arg0)
}

// SetVersion mocks base method.
func (m *MockAggregate) SetVersion(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetVersion", arg0)
}

// SetVersion indicates an expected call of SetVersion.
func (mr *MockAggregateMockRecorder) SetVersion(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVersion", reflect.TypeOf((*MockAggregate)(nil).SetVersion), arg0)
}

// Version mocks base method.
func (m *MockAggregate) Version() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(int)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockAggregateMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockAggregate)(nil).Version))
}
