// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: depotpb/api.proto

package depotpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	StoreId       string                 `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_depotpb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_depotpb_api_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ShoppingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Stops         map[string]*Stop       `protobuf:"bytes,3,rep,name=stops,proto3" json:"stops,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AssignedBodId string                 `protobuf:"bytes,4,opt,name=assigned_bod_id,json=assignedBodId,proto3" json:"assigned_bod_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingList) Reset() {
	*x = ShoppingList{}
	mi := &file_depotpb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingList) ProtoMessage() {}

func (x *ShoppingList) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingList.ProtoReflect.Descriptor instead.
func (*ShoppingList) Descriptor() ([]byte, []int) {
	return file_depotpb_api_proto_rawDescGZIP(), []int{1}
}

func (x *ShoppingList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShoppingList) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShoppingList) GetStops() map[string]*Stop {
	if x != nil {
		return x.Stops
	}
	return nil
}

func (x *ShoppingList) GetAssignedBodId() string {
	if x != nil {
		return x.AssignedBodId
	}
	return ""
}

func (x *ShoppingList) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Stop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreName     string                 `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	StoreLocation string                 `protobuf:"bytes,2,opt,name=store_location,json=storeLocation,proto3" json:"store_location,omitempty"`
	Items         map[string]*Item       `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stop) Reset() {
	*x = Stop{}
	mi := &file_depotpb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_depotpb_api_proto_rawDescGZIP(), []int{2}
}

func (x *Stop) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *Stop) GetStoreLocation() string {
	if x != nil {
		return x.StoreLocation
	}
	return ""
}

func (x *Stop) GetItems() map[string]*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_depotpb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_depotpb_api_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateShoppingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShoppingListRequest) Reset() {
	*x = CreateShoppingListRequest{}
	mi := &file_depotpb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShoppingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShoppingListRequest) ProtoMessage() {}

func (x *CreateShoppingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShoppingListRequest.ProtoReflect.Descriptor instead.
func (*CreateShoppingListRequest) Descriptor() ([]byte, []int) {
	return file_depotpb_api_proto_rawDescGZIP(), []int{4}
}

func (x *CreateShoppingListRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateShoppingListRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateShoppingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShoppingListResponse) Reset() {
	*x = CreateShoppingListResponse{}
	mi := &file_depotpb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShoppingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShoppingListResponse) ProtoMessage() {}

func (x *CreateShoppingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShoppingListResponse.ProtoReflect.Descriptor instead.
func (*CreateShoppingListResponse) Descriptor() ([]byte, []int) {
	return file_depotpb_api_proto_rawDescGZIP(), []int{5}
}

func (x *CreateShoppingListResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelShoppingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShoppingListRequest) Reset() {
	*x = CancelShoppingListRequest{}
	mi := &file_depotpb_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShoppingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShoppingListRequest) ProtoMessage() {}

func (x *CancelShoppingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShoppingListRequest.ProtoReflect.Descriptor instead.
func (*CancelShoppingListRequest) Descriptor() ([]byte, []int) {
	return file_depotpb_api_proto_rawDescGZIP(), []int{6}
}

func (x *CancelShoppingListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelShoppingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShoppingListResponse) Reset() {
	*x = CancelShoppingListResponse{}
	mi := &file_depotpb_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShoppingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShoppingListResponse) ProtoMessage() {}

func (x *CancelShoppingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShoppingListResponse.ProtoReflect.Descriptor instead.
func (*CancelShoppingListResponse) Descriptor() ([]byte, []int) {
	return file_depotpb_api_proto_rawDescGZIP(), []int{7}
}

type AssignShoppingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BotId         string                 `protobuf:"bytes,2,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignShoppingListRequest) Reset() {
	*x = AssignShoppingListRequest{}
	mi := &file_depotpb_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignShoppingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignShoppingListRequest) ProtoMessage() {}

func (x *AssignShoppingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignShoppingListRequest.ProtoReflect.Descriptor instead.
func (*AssignShoppingListRequest) Descriptor() ([]byte, []int) {
	return file_depotpb_api_proto_rawDescGZIP(), []int{8}
}

func (x *AssignShoppingListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssignShoppingListRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type AssignShoppingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignShoppingListResponse) Reset() {
	*x = AssignShoppingListResponse{}
	mi := &file_depotpb_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignShoppingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignShoppingListResponse) ProtoMessage() {}

func (x *AssignShoppingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignShoppingListResponse.ProtoReflect.Descriptor instead.
func (*AssignShoppingListResponse) Descriptor() ([]byte, []int) {
	return file_depotpb_api_proto_rawDescGZIP(), []int{9}
}

type CompleteShoppingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteShoppingListRequest) Reset() {
	*x = CompleteShoppingListRequest{}
	mi := &file_depotpb_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteShoppingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteShoppingListRequest) ProtoMessage() {}

func (x *CompleteShoppingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteShoppingListRequest.ProtoReflect.Descriptor instead.
func (*CompleteShoppingListRequest) Descriptor() ([]byte, []int) {
	return file_depotpb_api_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteShoppingListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CompleteShoppingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteShoppingListResponse) Reset() {
	*x = CompleteShoppingListResponse{}
	mi := &file_depotpb_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteShoppingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteShoppingListResponse) ProtoMessage() {}

func (x *CompleteShoppingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteShoppingListResponse.ProtoReflect.Descriptor instead.
func (*CompleteShoppingListResponse) Descriptor() ([]byte, []int) {
	return file_depotpb_api_proto_rawDescGZIP(), []int{11}
}

var File_depotpb_api_proto protoreflect.FileDescriptor

const file_depotpb_api_proto_rawDesc = "" +
	"\n" +
	"\x11depotpb/api.proto\x12\adepotpb\"a\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\tR\astoreId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\xfa\x01\n" +
	"\fShoppingList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x126\n" +
	"\x05stops\x18\x03 \x03(\v2 .depotpb.ShoppingList.StopsEntryR\x05stops\x12&\n" +
	"\x0fassigned_bod_id\x18\x04 \x01(\tR\rassignedBodId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x1aG\n" +
	"\n" +
	"StopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.depotpb.StopR\x05value:\x028\x01\"\xc5\x01\n" +
	"\x04Stop\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\x12%\n" +
	"\x0estore_location\x18\x02 \x01(\tR\rstoreLocation\x12.\n" +
	"\x05items\x18\x03 \x03(\v2\x18.depotpb.Stop.ItemsEntryR\x05items\x1aG\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.depotpb.ItemR\x05value:\x028\x01\"6\n" +
	"\x04Item\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"`\n" +
	"\x19CreateShoppingListRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.depotpb.OrderItemR\x05items\",\n" +
	"\x1aCreateShoppingListResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19CancelShoppingListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\x1aCancelShoppingListResponse\"B\n" +
	"\x19AssignShoppingListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06bot_id\x18\x02 \x01(\tR\x05botId\"\x1c\n" +
	"\x1aAssignShoppingListResponse\"-\n" +
	"\x1bCompleteShoppingListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\x1cCompleteShoppingListResponse2\x98\x03\n" +
	"\fDepotService\x12_\n" +
	"\x12CreateShoppingList\x12\".depotpb.CreateShoppingListRequest\x1a#.depotpb.CreateShoppingListResponse\"\x00\x12_\n" +
	"\x12CancelShoppingList\x12\".depotpb.CancelShoppingListRequest\x1a#.depotpb.CancelShoppingListResponse\"\x00\x12_\n" +
	"\x12AssignShoppingList\x12\".depotpb.AssignShoppingListRequest\x1a#.depotpb.AssignShoppingListResponse\"\x00\x12e\n" +
	"\x14CompleteShoppingList\x12$.depotpb.CompleteShoppingListRequest\x1a%.depotpb.CompleteShoppingListResponse\"\x00Bo\n" +
	"\vcom.depotpbB\bApiProtoP\x01Z\x1amall/depot/depotpb/depotpb\xa2\x02\x03DXX\xaa\x02\aDepotpb\xca\x02\aDepotpb\xe2\x02\x13Depotpb\\GPBMetadata\xea\x02\aDepotpbb\x06proto3"

var (
	file_depotpb_api_proto_rawDescOnce sync.Once
	file_depotpb_api_proto_rawDescData []byte
)

func file_depotpb_api_proto_rawDescGZIP() []byte {
	file_depotpb_api_proto_rawDescOnce.Do(func() {
		file_depotpb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_depotpb_api_proto_rawDesc), len(file_depotpb_api_proto_rawDesc)))
	})
	return file_depotpb_api_proto_rawDescData
}

var file_depotpb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_depotpb_api_proto_goTypes = []any{
	(*OrderItem)(nil),                    // 0: depotpb.OrderItem
	(*ShoppingList)(nil),                 // 1: depotpb.ShoppingList
	(*Stop)(nil),                         // 2: depotpb.Stop
	(*Item)(nil),                         // 3: depotpb.Item
	(*CreateShoppingListRequest)(nil),    // 4: depotpb.CreateShoppingListRequest
	(*CreateShoppingListResponse)(nil),   // 5: depotpb.CreateShoppingListResponse
	(*CancelShoppingListRequest)(nil),    // 6: depotpb.CancelShoppingListRequest
	(*CancelShoppingListResponse)(nil),   // 7: depotpb.CancelShoppingListResponse
	(*AssignShoppingListRequest)(nil),    // 8: depotpb.AssignShoppingListRequest
	(*AssignShoppingListResponse)(nil),   // 9: depotpb.AssignShoppingListResponse
	(*CompleteShoppingListRequest)(nil),  // 10: depotpb.CompleteShoppingListRequest
	(*CompleteShoppingListResponse)(nil), // 11: depotpb.CompleteShoppingListResponse
	nil,                                  // 12: depotpb.ShoppingList.StopsEntry
	nil,                                  // 13: depotpb.Stop.ItemsEntry
}
var file_depotpb_api_proto_depIdxs = []int32{
	12, // 0: depotpb.ShoppingList.stops:type_name -> depotpb.ShoppingList.StopsEntry
	13, // 1: depotpb.Stop.items:type_name -> depotpb.Stop.ItemsEntry
	0,  // 2: depotpb.CreateShoppingListRequest.items:type_name -> depotpb.OrderItem
	2,  // 3: depotpb.ShoppingList.StopsEntry.value:type_name -> depotpb.Stop
	3,  // 4: depotpb.Stop.ItemsEntry.value:type_name -> depotpb.Item
	4,  // 5: depotpb.DepotService.CreateShoppingList:input_type -> depotpb.CreateShoppingListRequest
	6,  // 6: depotpb.DepotService.CancelShoppingList:input_type -> depotpb.CancelShoppingListRequest
	8,  // 7: depotpb.DepotService.AssignShoppingList:input_type -> depotpb.AssignShoppingListRequest
	10, // 8: depotpb.DepotService.CompleteShoppingList:input_type -> depotpb.CompleteShoppingListRequest
	5,  // 9: depotpb.DepotService.CreateShoppingList:output_type -> depotpb.CreateShoppingListResponse
	7,  // 10: depotpb.DepotService.CancelShoppingList:output_type -> depotpb.CancelShoppingListResponse
	9,  // 11: depotpb.DepotService.AssignShoppingList:output_type -> depotpb.AssignShoppingListResponse
	11, // 12: depotpb.DepotService.CompleteShoppingList:output_type -> depotpb.CompleteShoppingListResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_depotpb_api_proto_init() }
func file_depotpb_api_proto_init() {
	if File_depotpb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_depotpb_api_proto_rawDesc), len(file_depotpb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_depotpb_api_proto_goTypes,
		DependencyIndexes: file_depotpb_api_proto_depIdxs,
		MessageInfos:      file_depotpb_api_proto_msgTypes,
	}.Build()
	File_depotpb_api_proto = out.File
	file_depotpb_api_proto_goTypes = nil
	file_depotpb_api_proto_depIdxs = nil
}
