// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: depotpb/messages.proto

package depotpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Events
type ShoppingListCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingListCompleted) Reset() {
	*x = ShoppingListCompleted{}
	mi := &file_depotpb_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingListCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingListCompleted) ProtoMessage() {}

func (x *ShoppingListCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingListCompleted.ProtoReflect.Descriptor instead.
func (*ShoppingListCompleted) Descriptor() ([]byte, []int) {
	return file_depotpb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ShoppingListCompleted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShoppingListCompleted) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// Commands
type CreateShoppingList struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	OrderId       string                     `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*CreateShoppingList_Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShoppingList) Reset() {
	*x = CreateShoppingList{}
	mi := &file_depotpb_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShoppingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShoppingList) ProtoMessage() {}

func (x *CreateShoppingList) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShoppingList.ProtoReflect.Descriptor instead.
func (*CreateShoppingList) Descriptor() ([]byte, []int) {
	return file_depotpb_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShoppingList) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateShoppingList) GetItems() []*CreateShoppingList_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CancelShoppingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShoppingList) Reset() {
	*x = CancelShoppingList{}
	mi := &file_depotpb_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShoppingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShoppingList) ProtoMessage() {}

func (x *CancelShoppingList) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShoppingList.ProtoReflect.Descriptor instead.
func (*CancelShoppingList) Descriptor() ([]byte, []int) {
	return file_depotpb_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CancelShoppingList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InitiateShopping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateShopping) Reset() {
	*x = InitiateShopping{}
	mi := &file_depotpb_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateShopping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateShopping) ProtoMessage() {}

func (x *InitiateShopping) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateShopping.ProtoReflect.Descriptor instead.
func (*InitiateShopping) Descriptor() ([]byte, []int) {
	return file_depotpb_messages_proto_rawDescGZIP(), []int{3}
}

func (x *InitiateShopping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Replies
type CreatedShoppingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedShoppingList) Reset() {
	*x = CreatedShoppingList{}
	mi := &file_depotpb_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedShoppingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedShoppingList) ProtoMessage() {}

func (x *CreatedShoppingList) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedShoppingList.ProtoReflect.Descriptor instead.
func (*CreatedShoppingList) Descriptor() ([]byte, []int) {
	return file_depotpb_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CreatedShoppingList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateShoppingList_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	StoreId       string                 `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShoppingList_Item) Reset() {
	*x = CreateShoppingList_Item{}
	mi := &file_depotpb_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShoppingList_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShoppingList_Item) ProtoMessage() {}

func (x *CreateShoppingList_Item) ProtoReflect() protoreflect.Message {
	mi := &file_depotpb_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShoppingList_Item.ProtoReflect.Descriptor instead.
func (*CreateShoppingList_Item) Descriptor() ([]byte, []int) {
	return file_depotpb_messages_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateShoppingList_Item) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateShoppingList_Item) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *CreateShoppingList_Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_depotpb_messages_proto protoreflect.FileDescriptor

const file_depotpb_messages_proto_rawDesc = "" +
	"\n" +
	"\x16depotpb/messages.proto\x12\adepotpb\"B\n" +
	"\x15ShoppingListCompleted\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"\xc5\x01\n" +
	"\x12CreateShoppingList\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x126\n" +
	"\x05items\x18\x02 \x03(\v2 .depotpb.CreateShoppingList.ItemR\x05items\x1a\\\n" +
	"\x04Item\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\tR\astoreId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"$\n" +
	"\x12CancelShoppingList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10InitiateShopping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13CreatedShoppingList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idBt\n" +
	"\vcom.depotpbB\rMessagesProtoP\x01Z\x1amall/depot/depotpb/depotpb\xa2\x02\x03DXX\xaa\x02\aDepotpb\xca\x02\aDepotpb\xe2\x02\x13Depotpb\\GPBMetadata\xea\x02\aDepotpbb\x06proto3"

var (
	file_depotpb_messages_proto_rawDescOnce sync.Once
	file_depotpb_messages_proto_rawDescData []byte
)

func file_depotpb_messages_proto_rawDescGZIP() []byte {
	file_depotpb_messages_proto_rawDescOnce.Do(func() {
		file_depotpb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_depotpb_messages_proto_rawDesc), len(file_depotpb_messages_proto_rawDesc)))
	})
	return file_depotpb_messages_proto_rawDescData
}

var file_depotpb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_depotpb_messages_proto_goTypes = []any{
	(*ShoppingListCompleted)(nil),   // 0: depotpb.ShoppingListCompleted
	(*CreateShoppingList)(nil),      // 1: depotpb.CreateShoppingList
	(*CancelShoppingList)(nil),      // 2: depotpb.CancelShoppingList
	(*InitiateShopping)(nil),        // 3: depotpb.InitiateShopping
	(*CreatedShoppingList)(nil),     // 4: depotpb.CreatedShoppingList
	(*CreateShoppingList_Item)(nil), // 5: depotpb.CreateShoppingList.Item
}
var file_depotpb_messages_proto_depIdxs = []int32{
	5, // 0: depotpb.CreateShoppingList.items:type_name -> depotpb.CreateShoppingList.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_depotpb_messages_proto_init() }
func file_depotpb_messages_proto_init() {
	if File_depotpb_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_depotpb_messages_proto_rawDesc), len(file_depotpb_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_depotpb_messages_proto_goTypes,
		DependencyIndexes: file_depotpb_messages_proto_depIdxs,
		MessageInfos:      file_depotpb_messages_proto_msgTypes,
	}.Build()
	File_depotpb_messages_proto = out.File
	file_depotpb_messages_proto_goTypes = nil
	file_depotpb_messages_proto_depIdxs = nil
}
