// Code generated by MockGen. DO NOT EDIT.
// Source: mall/baskets/internal/application (interfaces: App)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mock.go -package=application mall/baskets/internal/application App
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	domain "mall/baskets/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockApp) AddItem(ctx context.Context, add AddItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, add)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockAppMockRecorder) AddItem(ctx, add any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockApp)(nil).AddItem), ctx, add)
}

// CancelBasket mocks base method.
func (m *MockApp) CancelBasket(ctx context.Context, cancel CancelBasket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBasket", ctx, cancel)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelBasket indicates an expected call of CancelBasket.
func (mr *MockAppMockRecorder) CancelBasket(ctx, cancel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBasket", reflect.TypeOf((*MockApp)(nil).CancelBasket), ctx, cancel)
}

// CheckoutBasket mocks base method.
func (m *MockApp) CheckoutBasket(ctx context.Context, checkout CheckoutBasket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckoutBasket", ctx, checkout)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckoutBasket indicates an expected call of CheckoutBasket.
func (mr *MockAppMockRecorder) CheckoutBasket(ctx, checkout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutBasket", reflect.TypeOf((*MockApp)(nil).CheckoutBasket), ctx, checkout)
}

// GetBasket mocks base method.
func (m *MockApp) GetBasket(ctx context.Context, get GetBasket) (*domain.Basket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBasket", ctx, get)
	ret0, _ := ret[0].(*domain.Basket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasket indicates an expected call of GetBasket.
func (mr *MockAppMockRecorder) GetBasket(ctx, get any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasket", reflect.TypeOf((*MockApp)(nil).GetBasket), ctx, get)
}

// RemoveItem mocks base method.
func (m *MockApp) RemoveItem(ctx context.Context, remove RemoveItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", ctx, remove)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockAppMockRecorder) RemoveItem(ctx, remove any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockApp)(nil).RemoveItem), ctx, remove)
}

// StartBasket mocks base method.
func (m *MockApp) StartBasket(ctx context.Context, start StartBasket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartBasket", ctx, start)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartBasket indicates an expected call of StartBasket.
func (mr *MockAppMockRecorder) StartBasket(ctx, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBasket", reflect.TypeOf((*MockApp)(nil).StartBasket), ctx, start)
}
