// Code generated by MockGen. DO NOT EDIT.
// Source: mall/search/internal/domain (interfaces: CustomerCacheRepository,CustomerRepository,OrderRepository,ProductCacheRepository,ProductRepository,StoreCacheRepository,StoreRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/domain/mock.go -package=domain mall/search/internal/domain CustomerCacheRepository,CustomerRepository,OrderRepository,ProductCacheRepository,ProductRepository,StoreCacheRepository,StoreRepository
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCustomerCacheRepository is a mock of CustomerCacheRepository interface.
type MockCustomerCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerCacheRepositoryMockRecorder is the mock recorder for MockCustomerCacheRepository.
type MockCustomerCacheRepositoryMockRecorder struct {
	mock *MockCustomerCacheRepository
}

// NewMockCustomerCacheRepository creates a new mock instance.
func NewMockCustomerCacheRepository(ctrl *gomock.Controller) *MockCustomerCacheRepository {
	mock := &MockCustomerCacheRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerCacheRepository) EXPECT() *MockCustomerCacheRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCustomerCacheRepository) Add(ctx context.Context, customerID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, customerID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockCustomerCacheRepositoryMockRecorder) Add(ctx, customerID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCustomerCacheRepository)(nil).Add), ctx, customerID, name)
}

// Find mocks base method.
func (m *MockCustomerCacheRepository) Find(ctx context.Context, customerID string) (*Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, customerID)
	ret0, _ := ret[0].(*Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCustomerCacheRepositoryMockRecorder) Find(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCustomerCacheRepository)(nil).Find), ctx, customerID)
}

// MockCustomerRepository is a mock of CustomerRepository interface.
type MockCustomerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerRepositoryMockRecorder is the mock recorder for MockCustomerRepository.
type MockCustomerRepositoryMockRecorder struct {
	mock *MockCustomerRepository
}

// NewMockCustomerRepository creates a new mock instance.
func NewMockCustomerRepository(ctrl *gomock.Controller) *MockCustomerRepository {
	mock := &MockCustomerRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerRepository) EXPECT() *MockCustomerRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockCustomerRepository) Find(ctx context.Context, customerID string) (*Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, customerID)
	ret0, _ := ret[0].(*Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCustomerRepositoryMockRecorder) Find(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCustomerRepository)(nil).Find), ctx, customerID)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockOrderRepository) Add(ctx context.Context, order *Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockOrderRepositoryMockRecorder) Add(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockOrderRepository)(nil).Add), ctx, order)
}

// Get mocks base method.
func (m *MockOrderRepository) Get(ctx context.Context, orderID string) (*Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, orderID)
	ret0, _ := ret[0].(*Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrderRepositoryMockRecorder) Get(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrderRepository)(nil).Get), ctx, orderID)
}

// Search mocks base method.
func (m *MockOrderRepository) Search(ctx context.Context, search SearchOrders) ([]Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, search)
	ret0, _ := ret[0].([]Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockOrderRepositoryMockRecorder) Search(ctx, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockOrderRepository)(nil).Search), ctx, search)
}

// UpdateStatus mocks base method.
func (m *MockOrderRepository) UpdateStatus(ctx context.Context, orderID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, orderID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdateStatus(ctx, orderID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdateStatus), ctx, orderID, status)
}

// MockProductCacheRepository is a mock of ProductCacheRepository interface.
type MockProductCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockProductCacheRepositoryMockRecorder is the mock recorder for MockProductCacheRepository.
type MockProductCacheRepositoryMockRecorder struct {
	mock *MockProductCacheRepository
}

// NewMockProductCacheRepository creates a new mock instance.
func NewMockProductCacheRepository(ctrl *gomock.Controller) *MockProductCacheRepository {
	mock := &MockProductCacheRepository{ctrl: ctrl}
	mock.recorder = &MockProductCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductCacheRepository) EXPECT() *MockProductCacheRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockProductCacheRepository) Add(ctx context.Context, productID, storeID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, productID, storeID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockProductCacheRepositoryMockRecorder) Add(ctx, productID, storeID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockProductCacheRepository)(nil).Add), ctx, productID, storeID, name)
}

// Find mocks base method.
func (m *MockProductCacheRepository) Find(ctx context.Context, productID string) (*Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, productID)
	ret0, _ := ret[0].(*Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockProductCacheRepositoryMockRecorder) Find(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProductCacheRepository)(nil).Find), ctx, productID)
}

// Rebrand mocks base method.
func (m *MockProductCacheRepository) Rebrand(ctx context.Context, productID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rebrand", ctx, productID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rebrand indicates an expected call of Rebrand.
func (mr *MockProductCacheRepositoryMockRecorder) Rebrand(ctx, productID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rebrand", reflect.TypeOf((*MockProductCacheRepository)(nil).Rebrand), ctx, productID, name)
}

// Remove mocks base method.
func (m *MockProductCacheRepository) Remove(ctx context.Context, productID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockProductCacheRepositoryMockRecorder) Remove(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockProductCacheRepository)(nil).Remove), ctx, productID)
}

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockProductRepository) Find(ctx context.Context, productID string) (*Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, productID)
	ret0, _ := ret[0].(*Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockProductRepositoryMockRecorder) Find(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProductRepository)(nil).Find), ctx, productID)
}

// MockStoreCacheRepository is a mock of StoreCacheRepository interface.
type MockStoreCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoreCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockStoreCacheRepositoryMockRecorder is the mock recorder for MockStoreCacheRepository.
type MockStoreCacheRepositoryMockRecorder struct {
	mock *MockStoreCacheRepository
}

// NewMockStoreCacheRepository creates a new mock instance.
func NewMockStoreCacheRepository(ctrl *gomock.Controller) *MockStoreCacheRepository {
	mock := &MockStoreCacheRepository{ctrl: ctrl}
	mock.recorder = &MockStoreCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreCacheRepository) EXPECT() *MockStoreCacheRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockStoreCacheRepository) Add(ctx context.Context, storeID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, storeID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockStoreCacheRepositoryMockRecorder) Add(ctx, storeID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockStoreCacheRepository)(nil).Add), ctx, storeID, name)
}

// Find mocks base method.
func (m *MockStoreCacheRepository) Find(ctx context.Context, storeID string) (*Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, storeID)
	ret0, _ := ret[0].(*Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockStoreCacheRepositoryMockRecorder) Find(ctx, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStoreCacheRepository)(nil).Find), ctx, storeID)
}

// Rename mocks base method.
func (m *MockStoreCacheRepository) Rename(ctx context.Context, storeID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", ctx, storeID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockStoreCacheRepositoryMockRecorder) Rename(ctx, storeID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockStoreCacheRepository)(nil).Rename), ctx, storeID, name)
}

// MockStoreRepository is a mock of StoreRepository interface.
type MockStoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoreRepositoryMockRecorder
	isgomock struct{}
}

// MockStoreRepositoryMockRecorder is the mock recorder for MockStoreRepository.
type MockStoreRepositoryMockRecorder struct {
	mock *MockStoreRepository
}

// NewMockStoreRepository creates a new mock instance.
func NewMockStoreRepository(ctrl *gomock.Controller) *MockStoreRepository {
	mock := &MockStoreRepository{ctrl: ctrl}
	mock.recorder = &MockStoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreRepository) EXPECT() *MockStoreRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockStoreRepository) Find(ctx context.Context, storeID string) (*Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, storeID)
	ret0, _ := ret[0].(*Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockStoreRepositoryMockRecorder) Find(ctx, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStoreRepository)(nil).Find), ctx, storeID)
}
